### PR TITLE
Properly set camera position when leaving planet

### LINKED ISSUE #10082: Dynamic Camera is jarring on take-off of newly purchased ships
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While using dynamic camera acceleration from #9638, if you launch with a ship for the first time (including new saves), the camera starts at the system center instead of by your ship.

As an aside, the dynamic camera probably shouldn't be including the launch of the ship. Ideally, there shouldn't be any dynamic camera acceleration - it should be a result of the player moving the ship, not necessarily the planet launching the ship (which is a result of this being an acceleration of the ship anyways).

Part of the goal of the dynamic camera is to have a more focused view based on your ship's travel, however, if it occurs while taking off, it is jarring and doesn't center around your ship in the beginning of a possible battle, so you immediately lose some  information (more-so with the issue of newly purchased ships).

### Steps to Reproduce

1. Either start a new save, or purchase a new ship.
2. Takeoff.
3. Notice the camera starts at the center of the system, and not around your ship.
4. Get motion sickness as the camera pans to your ship.

### Expected Behavior

When taking off from a planet, the camera should be at your ship.

### Screenshots

https://github.com/endless-sky/endless-sky/assets/93169396/072afb48-b552-4789-a9ec-a86b438695be

### Link to save file

Don't need a save, can just do this with a new one.

### Operating System

Windows 10

### Game Source

Built from source

### Game Version

v0.10.7 Continuous

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Koranir**
Fixes #10082, and deduplicates some code.

Works by setting camera position on `EnterSystem()` _after_ the initial ship positions are set, which was default-initialized to (0, 0) when buying ships before.

### CODE REVIEW

**Review by ziproot — APPROVED** [review]
I tested this PR and the bug is indeed no longer present with this PR.

File: source/Engine.cpp [hunk 1]
```diff
@@ -1592,22 +1593,11 @@ void Engine::CalculateStep()
...
-				flagship->Center(), pow(hyperspacePercentage, .5));
-			newCenterVelocity = flagship->Velocity();
-		}
-		else
-		{
-			newCenter = newCamera.first;
-			newCenterVelocity = newCamera.second;
-		}
+		const auto [newCameraCenter, newCameraVelocity] = NewCenter(center, centerVelocity,
+			flagship->Center(), flagship->Velocity(), flagship ->GetHyperspacePercentage() / 100.,
```
Comment (tibetiroka) [inline source/Engine.cpp:1597]:
```suggestion
			flagship->Center(), flagship->Velocity(), flagship->GetHyperspacePercentage() / 100.,
```

**Review by tibetiroka — APPROVED** [review]
