### PR TITLE
bugfix: Fix ships attempting to re-board boarded targets (#8228)

### LINKED ISSUE #8228: NPCs unable to board cause traffic jam
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Some NPCs (notably, Remnant ships) appear to be too fast to stop and position themselves over small disabled ships accurately, and effectively get stuck in an infinite loop of boarding attempts. This issue causes a whole lot of ships to effectively get stuck in a small corner of space, doing nothing of importance.

### Steps to Reproduce

1. Go to a Remnant system
2. Wait for a hostile raider to spawn in, and get disabled
3. Wait for them to group up on the disabled fighters

### Expected Behavior

NPCs should either thrust more carefully, not have so powerful engines, or disengage from their boarding attempts.

### Screenshots

image
image
image

### Link to save file

[Test Pilot.txt](https://github.com/endless-sky/endless-sky/files/10710384/Test.Pilot.txt)

### Operating System

EndeavourOS (kernel: 6.1.8-zen1-1)

### Game Source

ESLauncher2

### Game Version

3b2085a4f904b6380b76441bc24492cbc3f1241a

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by tibetiroka**
**Bugfix:** This PR fixes #8228

## Fix Details
It appears that the issue was caused by the NPCs re-targeting the ships they just boarded. At least, when I prevented that, it seems to have gone away.

## Testing Done
I couldn't reproduce the issue after this fix. The only similar issue was a bunch of Ibis ships overcorrecting on the target and thus not boarding, but I believe that's being fixed by #8343. Other ships seem to work just fine, even if there are Ibis ships attempting to board.

I have observed that some fleets jump away after the flagship finished boarding, even if the other ships haven't; not sure if that's a bug, or that it's introduced by this fix. (The fleets seem to work fine, they just don't all finish boarding.)

## Save File
Use the save file from the issue.

### CODE REVIEW

**Comment by Zitchas** [comment]
Awesome! I look forward to testing this. It sounds promising.

**Review by Hurleveur — COMMENTED** [review]
Shouldnt this logic be added to canPlunder instead?

**Comment by tibetiroka** [comment]
`canPlunder` is assigned outside of the loop, so I can't check whether a specific ship has been boarded. We don't actually use the variable after the loop though, so I guess I could move it in there, and add the extra check to it. Would that be better?

**Review by Hurleveur — APPROVED** [review]
best to get whatever we can get outside of the loop, like you did. I hadnt seen that it was there (phone xD)
good fix!

**Comment by Zitchas** [comment]
OK, I'm testing this out, and it seems to work: I waited around until the Remnant disabled a Palavret, and then each Remnant ship boarded it and then left. Now, the disabled Palavret has become just another waypoint in the system, with ships arriving and regularly boarding it, but I don't think anything is boarding it more than once. So it looks great. 

However, this has revealed another bug: Ships getting stuck on flotsam. There's currently a half dozen ships right now that are just flying back and forth overtop of a piece of flotsam, obviously not picking it up. And they keep going back and forth until the flotsam vanishes. I'll re-equip with enough scanners to actually do some decent scans and see if I can identify if the ships are full of cargo and just being stuck, or if there's something else going on.

**Comment by tibetiroka** [comment]
> Ships getting stuck on flotsam.

I have seen that twice while working on this PR, but I cannot reliably reproduce it. As of now, I have no idea what causes it, they should in theory still switch targets and the minimum pickup size is also checked. I have noticed that they are _extremely_ fixated on said flotsam; they don't even care about hostile targets entering the system.

(This is an independent issue though, not caused by this PR.)

**Comment by Zitchas** [comment]
I'm kind of getting the impression that these may be facets of problems in the target selection system. Related, but not the same issue. 

Boarding a disabled ship seems to have priority over picking up flotsam, so as long as that's an option, the flotsam fixation isn't visible. But with this fixing the disabled ship fixation, then the flotsam one is revealedd.

File: source/AI.cpp [hunk 1]
```diff
@@ -1259,7 +1259,7 @@ shared_ptr<Ship> AI::FindTarget(const Ship &ship) const
 
 		// Ships which only disable never target already-disabled ships.
 		if((person.Disables() || (!person.IsNemesis() && foe != oldTarget.get()))
-				&& foe->IsDisabled() && !canPlunder)
+				&& foe->IsDisabled() && (!canPlunder || (canPlunder && Has(ship, foe->shared_from_this(), ShipEvent::BOARD))))
```
Comment (warp-core) [inline source/AI.cpp:1262]:
```suggestion
				&& foe->IsDisabled() && (!canPlunder || Has(ship, foe->shared_from_this(), ShipEvent::BOARD)))
```
This might be easier to read?
(Also, I think your line length check doesn't count a tab as four characters. That ought to change.)

Comment (tibetiroka) [reply source/AI.cpp:1262]: > (Also, I think your line length check doesn't count a tab as four characters. That ought to change.)

I asked @quyykk when I was writing the script, and he said it should be one.

**Comment by Zitchas** [comment]
Just for reference, it looks like the "NPCs obsessing over a piece of flotsam" is probably the issues reported here:
https://github.com/endless-sky/endless-sky/issues/6476
