### PR TITLE
Fix remnant mission bug (scanning cloaked Starling) by adding a `decloaked` personality, plus some warp_core refactoring

### LINKED ISSUE #6126: Starling cloaks in Remnant Keystone testing missions
**Describe the bug**
The remnant Starling that the player is supposed to scan in the missions Remnant: Keystone Research 5 and 6 cloaks. The mission can only be completed by waiting for an ion storm to break the cloak.

**To Reproduce**
Do the missions.

**Expected behavior**
Starling doesn't cloak to make it easy to scan. Maybe a personality tag? Or a custom ship that doesn't have inbuilt cloaking?

**Screenshots**

WIndows 10 Continuous build via ESL2. Updated 18 July 2021

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

**Additional context**

### PR DESCRIPTION
**Pull request by UnorderedSigh**
**Bugfix:** Fixes #6126 wherein you must scan a Starling that often cloaks. Uses a new *decloaked* personality.

Also, I merged @warp-core's changes that refactored the cloaking logic. Mostly it changed indentation and removed unneeded variables. His changes are the vast majority of the lines.

## Fix Details
In both `Remnant: Keystone Research 5` and `Remnant: Keystone Research 6`:

```ruby
	npc "scan outfits" "save"
		government "Remnant (Research)"

		# This ship will not cloak, even if it has a cloaking device
		personality ... decloaked

		system "Peragenor"
		ship "Starling (Keystone)" "Winds of Light"
```

### Test 1: Test the feature directly

1. Put this in data/[cloaktest.txt](https://github.com/endless-sky/endless-sky/files/11709233/cloaktest.txt)
2. Depart
3. Land on a planet with a spaceport. (Avoid busy systems or Remnant.)
4. Visit the spaceport.
5. Depart. 
6. Try cloaking and decloaking. The Starlings will *not* cloak, but the Gulls will.

### Test 2: Try the missions
1. Load this: [Friction Diction~3024-12-14 buggy mission scan.txt](https://github.com/UnorderedSigh/endless-sky/files/11708007/Friction.Diction.3024-12-14.buggy.mission.scan.txt)
2. Fly to the next planet.
3. Play the mission.
4. Also play the next one.

## Save File
This save file can be used to verify the bugfix. The bug will occur when using `226df696e`, and will not occur when using this branch's build.
[Friction Diction~3024-12-14 buggy mission scan.txt](https://github.com/UnorderedSigh/endless-sky/files/11708007/Friction.Diction.3024-12-14.buggy.mission.scan.txt)

### CODE REVIEW

File: data/remnant/remnant 1 introduction.txt [hunk 1]
```diff
@@ -3324,7 +3324,7 @@ mission "Remnant: Keystone Research 5"
 				accept
 	npc "scan outfits" "save"
 		government "Remnant (Research)"
-		personality coward disables plunders staying surveillance target mining
+		personality coward disables plunders staying surveillance target mining decloaked
```
Comment (warp-core) [inline data/remnant/remnant 1 introduction.txt:3327]: Alphabetise.
```suggestion
		personality coward decloaked disables mining plunders staying surveillance target
```

File: data/remnant/remnant 1 introduction.txt [hunk 2]
```diff
@@ -3344,7 +3344,7 @@ mission "Remnant: Keystone Research 6"
 	source "Viminal"
 	npc "scan outfits" "save"
 		government "Remnant (Research)"
-		personality coward disables plunders staying surveillance target mining
+		personality coward disables plunders staying surveillance target mining decloaked
```
Comment (warp-core) [inline data/remnant/remnant 1 introduction.txt:3347]: Alphabetise.
```suggestion
		personality coward decloaked disables mining plunders staying surveillance target
```

File: source/AI.cpp [hunk 3]
```diff
@@ -415,7 +415,7 @@ void AI::UpdateKeys(PlayerInfo &player, Command &activeCommands)
 	// Only toggle the "cloak" command if one of your ships has a cloaking device.
 	if(activeCommands.Has(Command::CLOAK))
 		for(const auto &it : player.Ships())
-			if(!it->IsParked() && it->Attributes().Get("cloak"))
+			if(!it->IsParked() && it->CanCloak())
```
Comment (warp-core) [inline source/AI.cpp:418]: Is it possible for a ship in this collection to have the decloaked personality?

File: source/AI.cpp [hunk 4]
```diff
@@ -2854,7 +2854,7 @@ bool AI::DoHarvesting(Ship &ship, Command &command) const
 // Check if this ship should cloak. Returns true if this ship decided to run away while cloaking.
 bool AI::DoCloak(Ship &ship, Command &command)
 {
-	if(ship.Attributes().Get("cloak"))
+	if(ship.CanCloak())
```
Comment (warp-core) [inline source/AI.cpp:2857]: I would prefer checking the personality first and bailing out instead.

You know what? This whole thing is bad. https://github.com/UnorderedSigh/endless-sky/pull/32

I've used the two things individually instead of calling Ship::CanCloak because I think the decision of whether or not to cloak should be made in AI, not Ship.

Comment (UnorderedSigh) [reply source/AI.cpp]: I removed Ship::CanCloak, and everything checks the personality directly instead.

Comment (UnorderedSigh) [reply source/AI.cpp]: I've merged @warp-core's changes, but they refactored the cloaking logic. I will need to test cloaking to make sure it still works.

Comment (UnorderedSigh) [reply source/AI.cpp]: I did some simple testing, and cloaking appears to be working after @warp-core's changes.

**Review by warp-core — APPROVED** [review]

**Comment by UnorderedSigh** [comment]
The only way I can see this happening is if the Starling is damaged and an enemy is in the system. Regardless of *why* it was happening, it won't happen anymore.

Also, independently of that bug, being able to prevent a fleet from cloaking has uses regardless. You won't need to make cloak vs. no-cloak versions of ships for different situations. Just give it the "decloaked" personality and you're done.

**Comment by UnorderedSigh** [comment]
By the way, I was unable to reproduce the bug, but I didn't try as hard as I could have. If you add a Korath NPC in the system that doesn't have heat weapons, it may trigger the bug. This PR will prevent the Starling from cloaking, no matter how bad it wants to, so whatever was wrong will be fixed.

**Comment by Zitchas** [comment]
Oh, definitely. The decloaked personality does have some significant and useful possibilities.

Although with that, I'm kind of inclined to think that maybe a middle ground might be useful. 
- Always cloak: Cloak whenever possible unless actively doing something that it needs to be decloaked for.
- Never cloak: Ship never cloaks, ever.
- Minimize cloaking: Ship only cloaks when it has taken massive damage and/or is *extremely* outgunned and is likely to be dead imminently.
- (normal): Ship cloaks when tactically useful to do so (break enemy locks, swarms of missiles, incoming DPS exceeds outgoing DPS, etc.
-

**Comment by UnorderedSigh** [comment]
The "middle ground" you are requesting would require quite a lot of coding, especially the later two. The code doesn't really know about incoming DPS or swarms of missiles. Nor does if have the smarts to tell if it is outgunned or likely to die immediately.

I'd like this PR to *just* implement option 2 in your list: never cloak.
