### PR TITLE
Fix bug "pressing 't' twice on a planet kills you" with a tribute confirmation dialog.

### LINKED ISSUE #8276: Accidentally Hitting T After Hailing a Planet Demands Ransom Resulting in Escorts Killing You
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was playing one of the Pug missions where I had a bunch of navy escorts and accidentally hit T after hailing a republic planet. I was significantly outnumbered so my escorts would kill me if I stayed in one place. I ended up editing my save file.

Adding an "Are you sure?" prompt would be nice so I don't demand tribute by accident and get killed by my escorts.

### Steps to Reproduce

1. Hail a planet
2. Bump T
3. Die

### Expected Behavior

1. Hail a planet.
2. Bump T
3. Prompt: "Are you sure you want to commit suicide [Demand Tribute]? No? Ok."

### Screenshots

_No response_

### Link to save file

I didn't want to dig up my original save, so I recreated it on purpose. Same behavior. I just hit T on purpose instead of by accident.

[Josh M_exported~3022-12-02 Hostile Republic.txt](https://github.com/endless-sky/endless-sky/files/10608171/Josh.M_exported.3022-12-02.Hostile.Republic.txt)

### Operating System

Linux Mint 20 (essentially Ubuntu)

### Game Source

GitHub Releases

### Game Version

v0.9.16

### Additional Information

This issue is related https://github.com/endless-sky/endless-sky/issues/5293 but I don't want the key changed, I just want it to be a little harder to accidentally demand tribute.

### LINKED ISSUE #8277: Your Escorts Won't Kill You During the Pug Missions
### Problem Description

I have not successfully made it through the Pug Missions without having a hostile escort fleet. Re: https://github.com/endless-sky/endless-sky/issues/8276 and https://github.com/endless-sky/endless-sky/issues/7617

I don't want to be killed by my escorts or need to edit my save file.

### Related Issue Links

Hostile escorts in general: https://github.com/endless-sky/endless-sky/issues/5154

### Desired Solution

I want to be able to go through the Pug Missions without hostile escorts.

That would likely require either setting the reputation with the Republic and Syndicate really good and resetting it after the missions or somehow interrupting the reputation system for the missions.

### Alternative Approaches

Those are the only solutions I can think of.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by UnorderedSigh**
**Bugfix:** Fixes #8277 and fixes #8276 wherein accidentally pressing "T" after hailing a planet causes you to die. This adds a confirmation dialog when demanding tribute.

This replaces the orphaned PR #8076, which I didn't notice before writing this one.

A related issue, #7946, complains that the tributes are not story-appropriate, and asks for the player to be warned of that. Such a warning seems to fourth-wall-breaking to me. Instead, I just warn them not to do it, and provide in-game-appropriate justifications.

## Fix Details
demand-tribute

## Testing Done
Demanded tribute.

## Save File
This save file can be used to verify the bugfix. The bug will occur when using `226df696e`, and will not occur when using this branch's build.
[Friction Diction.txt](https://github.com/endless-sky/endless-sky/files/11709153/Friction.Diction.txt)

Just depart and demand tribute.

### CODE REVIEW

**Comment by UnorderedSigh** [comment]
I meant to send this to my fork first.

File: source/HailPanel.cpp [hunk 1]
```diff
@@ -265,7 +266,11 @@ bool HailPanel::KeyDown(SDL_Keycode key, Uint16 mod, const Command &command, boo
 			message = "Thank you for granting us our freedom!";
 		}
 		else
-			message = planet->DemandTribute(player);
+			GetUI()->Push(new Dialog(this, &HailPanel::TributeConfirmed,
+				"Demanding tribute may cause this planet to launch defense fleets to fight you. "
+				"Those defense fleets may be from another government than the planet. "
```
Comment (quyykk) [inline source/HailPanel.cpp:271]: I don't get the point of that sentence, it sounds overly technical if that makes sense?  Maybe instead add something like that it would cause a major reputation? just my 2c

Comment (UnorderedSigh) [reply source/HailPanel.cpp]: I changed the message and made "cancel" the default button. Also, I changed it so the message only shows up before the tribute battle. Once the tribute battle has begun, the message serves no purpose.

tribute-mk2

Comment (TomGoodIdea) [reply source/HailPanel.cpp]: IMO it still doesn't sound great, particularly this sentence: `Once you defeat all of the tribute fleets, demand tribute again to receive a daily payment.`
It sounds like there was a rule (I know there is, but from the player's perspective it's not obvious) that dominated planets always give you _daily payments_. Also the "demand tribute again" thing sounds a bit too technical - if you demand tribute and the only thing they give you is a battle, it's pretty obvious you need to resend your demand, but idk.

Comment (UnorderedSigh) [reply source/HailPanel.cpp]: Do you have suggestions on how to reword it?

The player does need to know to keep making the demand. The timing of your second demand isn't immediately apparent. Of course, I could remove that sentence and let the player figure it out.

Comment (UnorderedSigh) [reply source/HailPanel.cpp]: > Demanding tribute may cause this planet to launch defense fleets to fight you.  After battling the fleets, you can keep demanding tribute until the planet relents.
> This barbaric act may hurt your reputation severely. Do you want to proceed?

Comment (TomGoodIdea) [reply source/HailPanel.cpp]: Could you make the first part a `help` message (activated the first time the player closes the hail panel after "Our defense fleet will make short work of you" response) and leave only the reputation warning?

Comment (UnorderedSigh) [reply source/HailPanel.cpp]: No, because you don't know yet whether the planet will accept the challenge.

Comment (TomGoodIdea) [reply source/HailPanel.cpp]: wdym?

Comment (UnorderedSigh) [reply source/HailPanel.cpp]: This warning happens before the player actually sends the message.

Comment (UnorderedSigh) [reply source/HailPanel.cpp]: In other words, the player has not demanded tribute yet. The warning is to not demand tribute unless you're ready for what is to come. They won't know whether the demand is met until they make the demand.

**Comment by warp-core** [comment]
Related: #7946, #8076.

File: source/HailPanel.cpp [hunk 2]
```diff
@@ -296,6 +297,12 @@ bool HailPanel::KeyDown(SDL_Keycode key, Uint16 mod, const Command &command, boo
 			player.SetTribute(planet, 0);
 			message = "Thank you for granting us our freedom!";
 		}
+		else if(!planet->IsDefending())
+			GetUI()->Push(new Dialog([this]() { message = planet->DemandTribute(player); },
+				"Demanding tribute may cause this planet to launch defense fleets to fight you. "
+				"After battling the fleets, you can keep demanding tribute until the planet relents.\n"
+				"This barbaric act may hurt your reputation severely. Do you want to proceed?",
+				Truncate::NONE, true, false));
```
Comment (Amazinite) [inline source/HailPanel.cpp:305]: "Keep demanding tribute" implies to me that you need to repeatedly demand tribute in order for it to succeed, when in reality it's just a single demand to start the battle and another single demand after the battle is over to get the tribute.
```suggestion
		else if(!planet->IsDefending())
			GetUI()->Push(new Dialog([this]() { message = planet->DemandTribute(player); },
				"Demanding tribute may cause this planet to launch defense fleets to fight you. "
				"After battling the fleets, you can demand tribute again for the planet to relent.\n"
				"This act may hurt your reputation severely. Do you want to proceed?",
				Truncate::NONE, true, false));
```

Comment (UnorderedSigh) [reply source/HailPanel.cpp]: I have updated the PR description screenshot with this new dialog.

**Comment by UnorderedSigh** [comment]
Last tested and known to work Sun, 20 Aug 2023 14:15:42 UTC.

File: source/Dialog.h [hunk 3]
```diff
@@ -38,6 +38,10 @@ class System;
 // callback function can be given to receive the player's response.
 class Dialog : public Panel {
 public:
+	// An OK / Cancel dialog where Cancel can be disabled. The okIsActive lets
+	// you select whether "OK" (true) or "Cancel" (false) are selected.
```
Comment (Amazinite) [inline source/Dialog.h:42]:
```suggestion
	// An OK / Cancel dialog where Cancel can be disabled. The okIsActive lets
	// you select whether "OK" (true) or "Cancel" (false) are selected as the default option.
```

**Comment by Hurleveur** [comment]
We could also modify the dialog to mention tributing is not cannon but that's another issue entirely for sure
