### PR TITLE
Apply swizzle when departing to any carried ships too.

### LINKED ISSUE #5936: Swizzle changes don't apply to carried ships
**Describe the bug**
If an event changes the swizzle of the player, after departing the swizzle of normal ships is modified accordingly but not for carried ships (drones and fighters) until those are launched

**To Reproduce**
1. Buy some ships capable of carrying fighters/drones and said fighters/drones
2. Use an event to change your swizzle
3. Depart

**Expected behavior**
Carried ships should change swizzle

**Screenshots**
Screenshot (619)
After departing having changed the swizzle from 5 to 0
Screenshot (620)
After launching the fighters

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: ESLauncher2
 - Version: lastest nightly

### PR DESCRIPTION
**Pull request by quyykk**
**Bugfix:** This PR fixes #5936 

## Fix Details

When `Place`ing a `Ship` (which happens when departing from a planet) the ship swizzle is updated. This fix updates any carried ships' swizzle too.

## Testing Done
Tested the save file below.

## Save File
This save file is adapted from the save file from the linked issue.
[tommaso.becca.txt](https://github.com/endless-sky/endless-sky/files/6839453/tommaso.becca.txt)

### CODE REVIEW

File: source/Ship.cpp [hunk 1]
```diff
@@ -1155,7 +1155,17 @@ void Ship::Place(Point position, Point velocity, Angle angle)
...
-		SetSwizzle(customSwizzle >= 0 ? customSwizzle : government->GetSwizzle());
+	{
+		auto swizzle = customSwizzle >= 0 ? customSwizzle : government->GetSwizzle();
+		SetSwizzle(swizzle);
+
+		// Set swizzle for any carried ships too.
+		for(const auto &bay : bays)
+		{
+			if(bay.ship)
+				bay.ship->SetSwizzle(swizzle);
```
Comment (tehhowch) [inline source/Ship.cpp:1166]: You will want to use each carried ship's custom swizzle, if it has one.

**Review by tehhowch — COMMENTED** [review]
I've not play-tested this yet, just an observation.

File: source/Ship.cpp (hunk 1 above)
Comment (quyykk) [reply source/Ship.cpp]: You're right! fixed

**Comment by tehhowch** [comment]
@beccabunny please verify if this fixes the issue

**Comment by petervdmeer** [comment]
I tested this fix (by replaying the swizzle-mission/events as described in #5936 both without and with this fix) and I can confirm that this fix solves the issue that was described in #5936.
(The savegame was missing some data to reproduce the issue, but the information given was sufficiently clear to reproduce without the savegame.)
