### PR TITLE
fix(UI): Unlimited planets supported by UI + enhancement to planet displays in map

### LINKED ISSUE #2230: More than 3 landable planets in a system pushes UI off screen
long title short:
overlap ui
my laptop has a 1600x900 screen and the left bottom stuff gets cluttered
checked for duplicates but didn't find any about this (but didn't click every single issue)

### PR DESCRIPTION
**Pull request by Hurleveur**
-----------------------
**Bugfix:** This PR should resolve #2230 

<details><summary>How it looks now when there are too many planets. I'm quite proud of this one !</summary>

viminal
And here is how it looks with only 2 planets.
markeb
</details>

## Fix Details
This prevents too many planets from showing up on screen and ruining your display. Instead you will have a scrollable menu like for the one of the map outfitter panel except this one is dynamic, it's height changes based on the requirements (aka the amount of planets in the system).

## Testing Done
I modified the map file to show all remnant worlds (that were hidden because of the bug this PR fixes) and used that, I tried to change system by clicking/pressing tab or "j" which does reset the scrolling, you can't scroll too much either up or down. I also tried to select the categories like shipyard, uninhabited, has been visited etc which works. If there is a system behind the arrow and you click on the arrow it won't select the system.

## Save File
Any save file that sees the remnant capital system with Viminal can test this, just click on it in the map and you will see. Don't have one unfortunately because I filled my main save with plugins.

- [x] added a pr to high dpi, [#193](https://github.com/endless-sky/endless-sky-high-dpi/pull/193)

### CODE REVIEW

**Comment by Zitchas** [comment]
Looks really good with these new arrows. They are clear and to the point, and look good. It'll be very nice to have this list of planets scroll.

File: source/MapDetailPanel.cpp [hunk 1]
```diff
@@ -122,13 +122,31 @@ void MapDetailPanel::Draw()
...
+bool MapDetailPanel::Scroll(double dx, double dy)
+{
+	Point point = UI::GetMouse();
+	if(excessPlanet && point.X() < Screen::Left() + 160 && point.Y() > Screen::Top() + 90 && point.Y() < Screen::Bottom() - 230)
+	{
+		if(dy > 0. && firstPlanet < excessPlanet)
+			++firstPlanet;
+		else if(dy < 0. && firstPlanet > 0)
+			--firstPlanet;
+		return true;
```
Comment (tehhowch) [inline source/MapDetailPanel.cpp:134]: This snaps to the next item without any actual _scroll_, which is not exactly stellar UX.

**Review by tehhowch — CHANGES_REQUESTED** [review]
Ideally we would not continue to add tech debt as is done here, by adding new, hardcoded UI element positions.

(All of the map panels are in need of refactoring to use only positions and items defined in an associated `"interface"` node, so that users and plugin authors can lay out content on the screen in a manner of their own choosing, and the content aligns and expands appropriately relative to the window and other content.
One would register click zones, scrollable lists, and so on, in that paradigm.)

I don't expect you to refactor all of that here, but I do expect the manual "scrolled list" to scroll.

File: source/MapDetailPanel.cpp (hunk 1 above)
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:134]: I like it to be one system at a time, scrolling is a big word indeed but having half of planets would mean complication for finding where you clicked that would be completely unecessary
most importantly, having half of planets view would simply be unbearable in terms of how it looks according to me

but I'm open to changes, I thought about having it scroll really, with the trade prices on the right and the same scrolling UI as for outfitterPanel etc, with planets being shown with their images and same stuff as now. However that would be too much information and in most of the times, useless, because only systems with more than 7 planets would use it and it would be weird looking to have that scrolling background sometimes be there or not, the idea of the system view is for it to be minimalist according to me.

File: source/MapDetailPanel.cpp [hunk 2]
```diff
@@ -488,52 +523,75 @@ void MapDetailPanel::DrawInfo()
...
+					++excessPlanet;
+				++currentPlanet;
 			}
 	}
+	// Hints that more planets can be seen by scrolling up.
+	if(excessPlanet > firstPlanet)
+	{
+		const Sprite *up = SpriteSet::Get("ui/up");
+		Point point(Screen::Left() + 98., governmentY + 35.);
+		SpriteShader::Draw(up, point);
```
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:586]: ooooh I didnt know about that I'll check if it looks right
will close the high dpi pr too if it works

File: source/MapDetailPanel.cpp [hunk 3]
```diff
@@ -488,52 +523,75 @@ void MapDetailPanel::DrawInfo()
...
-					dim);
-				if(commodity == SHOW_VISITED)
-					PointerShader::Draw(uiPoint + Point(-70., 35.), Point(1., 0.),
-						10.f, 10.f, 0.f, medium);
-				
-				uiPoint.Y() += 130.;
+				// Makes sure one more planet does not go out of the screen.
+				if(uiPoint.Y() <= (Screen::Bottom() - 230 - 130) && currentPlanet >= firstPlanet)
+				{
+					shown.insert(planet);
```
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:530]: I want to know how many planets don't show up on screen so I can prevent the case where you make less planets viewable than there were before, and also to display the arrows only when needed

File: source/MapDetailPanel.h [hunk 4]
```diff
@@ -58,6 +60,10 @@ class MapDetailPanel : public MapPanel {
 private:
 	int governmentY = 0;
 	int tradeY = 0;
+	// The first planet of the list that is displayed (used when there are too many to all fit at once).
+	int firstPlanet = 0;
```
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapDetailPanel.h:64]: haven't used one out of a for yet but I'll try to

File: source/MapDetailPanel.cpp (hunk 1 above)
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:134]: also for a true scroll one more variable, offset, would be required

File: source/MapDetailPanel.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:586]: pointers
none of them have quite the same look, I could settle for good enough I guess but I would prefer changing all scrolling indicators to this one instead of forgeting it (or just leaving them here)

**Comment by Hurleveur** [comment]
> I do expect the manual "scrolled list" to scroll.

Here is what I'm working on, does it seem like a more "perfected" version of this would satisfy you ? the code is way more complicated but you asked for it ;)
too many planets

File: source/MapDetailPanel.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapDetailPanel.cpp]: I used them even if they are worse, watever

**Comment by Hurleveur** [comment]
> Ideally we would not continue to add tech debt as is done here, by adding new, hardcoded UI element positions.
> 
> (All of the map panels are in need of refactoring to use only positions and items defined in an associated `"interface"` node, so that users and plugin authors can lay out content on the screen in a manner of their own choosing, and the content aligns and expands appropriately relative to the window and other content. One would register click zones, scrollable lists, and so on, in that paradigm.)
> 
> I don't expect you to refactor all of that here, but I do expect the manual "scrolled list" to scroll.

Well if this beauty isn't good enough of a scrolling list idk what is ;)

**Comment by Zitchas** [comment]
Just curious, does the white arrow next to shipyard in the image signify?

**Comment by Hurleveur** [comment]
> Just curious, does the white arrow next to shipyard in the image signify?

as before, you can select shipyards and spaceport etc and it shows them on the map

**Comment by Zitchas** [comment]
So, this is just waiting for a final review? Still looks good. Looking forward to having it in-game.

**Comment by samrocketman** [comment]
Running your code through clang-format produces the following diff.

<details><summary>View diff (click to expand)</summary>

```diff
diff --git a/source/MapDetailPanel.cpp b/source/MapDetailPanel.cpp
index 8e610c7f..d4ea618a 100644
--- a/source/MapDetailPanel.cpp
+++ b/source/MapDetailPanel.cpp
@@ -12,23 +12,16 @@ PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 
 #include "MapDetailPanel.h"
 
-#include "text/alignment.hpp"
 #include "Angle.h"
 #include "Color.h"
 #include "Command.h"
 #include "CoreStartData.h"
 #include "Dialog.h"
-#include "text/DisplayText.h"
-#include "text/Font.h"
-#include "text/FontSet.h"
-#include "text/Format.h"
 #include "FillShader.h"
 #include "GameData.h"
 #include "Government.h"
-#include "text/layout.hpp"
 #include "MapOutfitterPanel.h"
 #include "MapShipyardPanel.h"
-#include "pi.h"
 #include "Planet.h"
 #include "PlayerInfo.h"
 #include "PointerShader.h"
@@ -44,9 +37,16 @@ PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 #include "StellarObject.h"
 #include "System.h"
 #include "Trade.h"
-#include "text/truncate.hpp"
 #include "UI.h"
+#include "pi.h"
+#include "text/DisplayText.h"
+#include "text/Font.h"
+#include "text/FontSet.h"
+#include "text/Format.h"
 #include "text/WrappedText.h"
+#include "text/alignment.hpp"
+#include "text/layout.hpp"
+#include "text/truncate.hpp"
 
 #include <algorithm>
 #include <cmath>
@@ -64,20 +64,20 @@ namespace {
 	{
 		// Rotate the given point by the reference amount.
 		Point rotated(reference.Dot(point), reference.Cross(point));
-		
+
 		// This will be the tiebreaker value: the length, squared.
 		double length = rotated.Dot(rotated);
 		// Calculate the angle, but rotated 180 degrees so that the discontinuity
 		// comes at the reference angle rather than directly opposite it.
 		double angle = atan2(-rotated.Y(), -rotated.X());
-		
+
 		// Special case: collinear with the reference vector. If the point is
 		// a longer vector than the reference, it's the very best angle.
 		// Otherwise, it is the very worst angle. (Note: this also is applied if
 		// the angle is opposite (angle == 0) but then it's a no-op.)
 		if(!rotated.Y())
 			angle = copysign(angle, rotated.X() - reference.Dot(reference));
-		
+
 		// Return the angle, plus the length as a tie-breaker.
 		return make_pair(angle, length);
 	}
@@ -115,7 +115,7 @@ void MapDetailPanel::Step()
 void MapDetailPanel::Draw()
 {
 	MapPanel::Draw();
-	
+
 	DrawInfo();
 	DrawOrbits();
 	DrawKey();
@@ -126,13 +126,14 @@ void MapDetailPanel::Draw()
 bool MapDetailPanel::Scroll(double dx, double dy)
 {
 	Point point = UI::GetMouse();
-	if(maxScroll && point.X() < Screen::Left() + 160 && point.Y() > Screen::Top() + 90 && point.Y() < Screen::Bottom() - 230)
+	if(maxScroll && point.X() < Screen::Left() + 160 && point.Y() > Screen::Top() + 90
+		&& point.Y() < Screen::Bottom() - 230)
 	{
 		if(dy > 0. && scroll > dy * 25.)
 			scroll -= dy * 25.;
 		else if(dy < 0. && scroll - dy * 25. < maxScroll)
 			scroll -= dy * 25.;
-			
+
 		return true;
 	}
 	else
@@ -166,12 +167,12 @@ bool MapDetailPanel::KeyDown(SDL_Keycode key, Uint16 mod, const Command &command
 		}
 		Point here = source->Position();
 		const System *original = next;
-		
+
 		// Depending on whether the flagship has a jump drive, the possible links
 		// we can travel along are different:
 		bool hasJumpDrive = player.Flagship()->Attributes().Get("jump drive");
 		const set<const System *> &links = hasJumpDrive ? source->JumpNeighbors(player.Flagship()->JumpRange()) : source->Links();
-		
+
 		// For each link we can travel from this system, check whether the link
 		// is closer to the current angle (while still being larger) than any
 		// link we have seen so far.
@@ -187,7 +188,7 @@ bool MapDetailPanel::KeyDown(SDL_Keycode key, Uint16 mod, const Command &command
 				continue;
 			if(!(hasJumpDrive || player.HasVisited(*it) || player.HasVisited(*source)))
 				continue;
-			
+
 			// Generate a sortable angle with vector length as a tiebreaker.
 			// Otherwise if two systems are in exactly the same direction it is
 			// not well defined which one comes first.
@@ -226,7 +227,7 @@ bool MapDetailPanel::KeyDown(SDL_Keycode key, Uint16 mod, const Command &command
 	}
 	else
 		return MapPanel::KeyDown(key, mod, command, isNewPress);
-	
+
 	return true;
 }
 
@@ -264,7 +265,7 @@ bool MapDetailPanel::Click(int x, int y, int clicks)
 						static const int SHOW[4] = {
 							SHOW_REPUTATION, SHOW_SHIPYARD, SHOW_OUTFITTER, SHOW_VISITED};
 						SetCommodity(SHOW[row]);
-						
+
 						// Double-click the Shipyard or Outfitter line to open that map view.
 						if(clicks > 1 && SHOW[row] == SHOW_SHIPYARD)
 						{
@@ -299,10 +300,10 @@ bool MapDetailPanel::Click(int x, int y, int clicks)
 		}
 		if(selectedPlanet && player.Flagship())
 			player.SetTravelDestination(selectedPlanet);
-		
+
 		return true;
 	}
-	
+
 	const System *const &previous = selectedSystem;
 	// The click was not on an interface element, so check if it was on a system.
 	MapPanel::Click(x, y, clicks);
@@ -331,7 +332,7 @@ bool MapDetailPanel::RClick(int x, int y)
 		auto uiClick = Point(x, y) - orbitCenter;
 		if(uiClick.Length() > 130)
 			return true;
-		
+
 		// Only issue movement orders if the player is in-flight.
 		if(player.GetPlanet())
 			GetUI()->Push(new Dialog("You cannot issue fleet movement orders while docked."));
@@ -340,7 +341,7 @@ bool MapDetailPanel::RClick(int x, int y)
 		else
 			player.SetEscortDestination(selectedSystem, uiClick / scale);
 	}
-	
+
 	return true;
 }
 
@@ -353,11 +354,11 @@ void MapDetailPanel::DrawKey()
 	const Color &dim = *GameData::Colors().Get("dim");
 	const Color &medium = *GameData::Colors().Get("medium");
 	const Font &font = FontSet::Get(14);
-	
+
 	Point pos = Screen::TopRight() + Point(-110., 310.);
 	Point headerOff(-5., -.5 * font.Height());
 	Point textOff(10., -.5 * font.Height());
-	
+
 	static const string HEADER[] = {
 		"Trade prices:",
 		"Ships for sale:",
@@ -370,7 +371,7 @@ void MapDetailPanel::DrawKey()
 	const string &header = HEADER[-min(0, max(-6, commodity))];
 	font.Draw(header, pos + headerOff, medium);
 	pos.Y() += 20.;
-	
+
 	if(commodity >= 0)
 	{
 		// Each system is colored by the selected commodity's price. Draw
@@ -379,7 +380,7 @@ void MapDetailPanel::DrawKey()
 		const auto &range = commodities[commodity];
 		if(static_cast<unsigned>(commodity) >= commodities.size())
 			return;
-		
+
 		for(int i = 0; i <= 3; ++i)
 		{
 			RingShader::Draw(pos, OUTER, INNER, MapColor(i * (2. / 3.) - 1.));
@@ -395,7 +396,7 @@ void MapDetailPanel::DrawKey()
 			{"None", "1", "5", "10+"},
 			{"None", "1", "30", "60+"}};
 		static const double VALUE[4] = {-1., 0., .5, 1.};
-		
+
 		for(int i = 0; i < 4; ++i)
 		{
 			RingShader::Draw(pos, OUTER, INNER, MapColor(VALUE[i]));
@@ -442,26 +443,26 @@ void MapDetailPanel::DrawKey()
 		RingShader::Draw(pos + Point(24., 0.), OUTER, INNER, ReputationColor(1e4, true, false));
 		font.Draw("Friendly", pos + textOff + Point(24., 0.), dim);
 		pos.Y() += 20.;
-		
+
 		RingShader::Draw(pos, OUTER, INNER, ReputationColor(-1e-1, false, false));
 		RingShader::Draw(pos + Point(12., 0.), OUTER, INNER, ReputationColor(-1e2, false, false));
 		RingShader::Draw(pos + Point(24., 0.), OUTER, INNER, ReputationColor(-1e4, false, false));
 		font.Draw("Hostile", pos + textOff + Point(24., 0.), dim);
 		pos.Y() += 20.;
-		
+
 		RingShader::Draw(pos, OUTER, INNER, ReputationColor(0., false, false));
 		font.Draw("Restricted", pos + textOff, dim);
 		pos.Y() += 20.;
-		
+
 		RingShader::Draw(pos, OUTER, INNER, ReputationColor(0., false, true));
 		font.Draw("Dominated", pos + textOff, dim);
 		pos.Y() += 20.;
 	}
-	
+
 	RingShader::Draw(pos, OUTER, INNER, UninhabitedColor());
 	font.Draw("Uninhabited", pos + textOff, dim);
 	pos.Y() += 20.;
-	
+
 	RingShader::Draw(pos, OUTER, INNER, UnexploredColor());
 	font.Draw("Unexplored", pos + textOff, dim);
 }
@@ -475,35 +476,35 @@ void MapDetailPanel::DrawInfo()
 	const Color &faint = *GameData::Colors().Get("faint");
 	const Color &dim = *GameData::Colors().Get("dim");
 	const Color &medium = *GameData::Colors().Get("medium");
-	
+
 	const Color &back = *GameData::Colors().Get("map side panel background");
 	// Draw the panel.
 	Point size(230., min((Screen::Height() - 360.), planetNbr * 130. + 75.));
 	FillShader::Fill(Point(Screen::Left() + size.X() / 2., Screen::Top() + size.Y() / 2.), size, back);
-	
+
 	// Edges:
 	const Sprite *bottom = SpriteSet::Get("ui/bottom edge");
 	Point pos(Screen::TopLeft());
 	Point edgePos = pos + Point(.5 * size.X(), size.Y());
 	Point bottomOff(-30., .5 * bottom->Height());
 	SpriteShader::Draw(bottom, edgePos + bottomOff);
-	
+
 	const Sprite *right = SpriteSet::Get("ui/right edge");
 	Point rightOff(.5 * (size.X() + right->Width()), -right->Height() / 2.);
 	SpriteShader::Draw(right, edgePos + rightOff);
-	
+
 	Point uiPoint(Screen::Left() + 100., Screen::Top() + 45.);
-	
+
 	// System sprite goes from 0 to 90.
 	const Sprite *systemSprite = SpriteSet::Get("ui/map system");
 	SpriteShader::Draw(systemSprite, uiPoint);
-	
+
 	const Font &font = FontSet::Get(14);
 	string systemName = player.KnowsName(*selectedSystem) ?
 		selectedSystem->Name() : "Unexplored System";
 	const auto alignLeft = Layout(140, Truncate::BACK);
 	font.Draw({systemName, alignLeft}, uiPoint + Point(-90., -7.), medium);
-	
+
 	governmentY = uiPoint.Y() + 10.;
 	string gov = player.HasVisited(*selectedSystem) ?
 		selectedSystem->GetGovernment()->GetName() : "Unknown Government";
@@ -511,7 +512,7 @@ void MapDetailPanel::DrawInfo()
 	if(commodity == SHOW_GOVERNMENT)
 		PointerShader::Draw(uiPoint + Point(-90., 20.), Point(1., 0.),
 			10.f, 10.f, 0.f, medium);
-	
+
 	uiPoint.Y() += 115.;
 	planetY.clear();
 	// Draw the basic information for visitable planets in this system.
@@ -532,58 +533,46 @@ void MapDetailPanel::DrawInfo()
 				const Planet *planet = object.GetPlanet();
 				if(planet->IsWormhole() || !planet->IsAccessible(player.Flagship()) || shown.count(planet))
 					continue;
-				
-				if((scroll - 65.)/ 130. <= planetNbr && uiPoint.Y() + int(scroll) % 130 < Screen::Bottom() - 295)
+
+				if((scroll - 65.) / 130. <= planetNbr && uiPoint.Y() + int(scroll) % 130 < Screen::Bottom() - 295)
 				{
 					shown.insert(planet);
-					
+
 					if(planet == selectedPlanet)
 						FillShader::Fill(Point(Screen::Left() + 110., uiPoint.Y()), Point(220., 110.), faint);
-					
+
 					bool hasSpaceport = planet->HasSpaceport();
 
 					const Sprite *sprite = object.GetSprite();
 					double scale = min(.5f, min((100) / sprite->Width(), (100) / sprite->Height()));
 					SpriteShader::Draw(sprite, Point(Screen::Left() + 50, uiPoint.Y()), scale);
 					planetY[planet] = uiPoint.Y() - 65;
-					
-					font.Draw({object.Name(), alignLeft},
-						uiPoint + Point(0., -52.),
+
+					font.Draw({ object.Name(), alignLeft }, uiPoint + Point(0., -52.),
 						planet == selectedPlanet ? medium : dim);
-					
-					string reputationLabel = !hasSpaceport ? "No Spaceport" :
+
+					string reputationLabel = !hasSpaceport			 ? "No Spaceport" :
 						GameData::GetPolitics().HasDominated(planet) ? "Dominated" :
-						planet->GetGovernment()->IsEnemy() ? "Hostile" :
-						planet->CanLand() ? "Friendly" : "Restricted";
-					font.Draw(reputationLabel,
-						uiPoint + Point(10., -32.),
-						hasSpaceport ? medium : faint);
+						planet->GetGovernment()->IsEnemy()			 ? "Hostile" :
+						planet->CanLand()							 ? "Friendly" :
+																		 "Restricted";
+					font.Draw(reputationLabel, uiPoint + Point(10., -32.), hasSpaceport ? medium : faint);
 					if(commodity == SHOW_REPUTATION)
-						PointerShader::Draw(uiPoint + Point(0. + 10., -25.), Point(1., 0.),
-							10.f, 10.f, 0.f, medium);
-					
-					font.Draw("Shipyard",
-						uiPoint + Point(10., -12.),
-						planet->HasShipyard() ? medium : faint);
+						PointerShader::Draw(uiPoint + Point(0. + 10., -25.), Point(1., 0.), 10.f, 10.f, 0.f, medium);
+
+					font.Draw("Shipyard", uiPoint + Point(10., -12.), planet->HasShipyard() ? medium : faint);
 					if(commodity == SHOW_SHIPYARD)
-						PointerShader::Draw(uiPoint + Point(0. + 10., -5.), Point(1., 0.),
-							10.f, 10.f, 0.f, medium);
-					
-					font.Draw("Outfitter",
-						uiPoint + Point(0. + 10., 8.),
-						planet->HasOutfitter() ? medium : faint);
+						PointerShader::Draw(uiPoint + Point(0. + 10., -5.), Point(1., 0.), 10.f, 10.f, 0.f, medium);
+
+					font.Draw("Outfitter", uiPoint + Point(0. + 10., 8.), planet->HasOutfitter() ? medium : faint);
 					if(commodity == SHOW_OUTFITTER)
-						PointerShader::Draw(uiPoint + Point(0. + 10., 15.), Point(1., 0.),
-							10.f, 10.f, 0.f, medium);
-							
+						PointerShader::Draw(uiPoint + Point(0. + 10., 15.), Point(1., 0.), 10.f, 10.f, 0.f, medium);
+
 					bool hasVisited = player.HasVisited(*planet);
-					font.Draw(hasVisited ? "(has been visited)" : "(not yet visited)",
-						uiPoint + Point(10., 28.),
-						dim);
+					font.Draw(hasVisited ? "(has been visited)" : "(not yet visited)", uiPoint + Point(10., 28.), dim);
 					if(commodity == SHOW_VISITED)
-						PointerShader::Draw(uiPoint + Point(0. + 10., 35), Point(1., 0.),
-							10.f, 10.f, 0.f, medium);
-					
+						PointerShader::Draw(uiPoint + Point(0. + 10., 35), Point(1., 0.), 10.f, 10.f, 0.f, medium);
+
 					uiPoint.Y() += 130.;
 				}
 				else
@@ -592,14 +581,14 @@ void MapDetailPanel::DrawInfo()
 			}
 		uiPoint.Y() += int(scroll) % 130;
 	}
-	
+
 	uiPoint.Y() += 50.;
 	tradeY = uiPoint.Y() - 95.;
-	
+
 	// Trade sprite goes after the rest.
 	const Sprite *tradeSprite = SpriteSet::Get("ui/map trade");
 	SpriteShader::Draw(tradeSprite, uiPoint);
-	
+
 	uiPoint.X() -= 90.;
 	uiPoint.Y() -= 97.;
 	for(const Trade::Commodity &commodity : GameData::Commodities())
@@ -608,11 +597,11 @@ void MapDetailPanel::DrawInfo()
 		if(static_cast<unsigned>(this->commodity) < GameData::Commodities().size())
 			isSelected = (&commodity == &GameData::Commodities()[this->commodity]);
 		const Color &color = isSelected ? medium : dim;
-		
+
 		font.Draw(commodity.name, uiPoint, color);
-		
+
 		string price;
-		
+
 		bool hasVisited = player.HasVisited(*selectedSystem);
 		if(hasVisited && selectedSystem->IsInhabited(player.Flagship()))
 		{
@@ -637,16 +626,16 @@ void MapDetailPanel::DrawInfo()
 		}
 		else
 			price = (hasVisited ? "n/a" : "?");
-		
+
 		const auto alignRight = Layout(140, Alignment::RIGHT, Truncate::BACK);
 		font.Draw({price, alignRight}, uiPoint, color);
-		
+
 		if(isSelected)
 			PointerShader::Draw(uiPoint + Point(0., 7.), Point(1., 0.), 10.f, 10.f, 0.f, color);
-		
+
 		uiPoint.Y() += 20.;
 	}
-	
+
 	if(selectedPlanet && !selectedPlanet->Description().empty()
 			&& player.HasVisited(*selectedPlanet) && !selectedPlanet->IsWormhole())
 	{
@@ -656,14 +645,14 @@ void MapDetailPanel::DrawInfo()
 		Point pos(Screen::Right() - X_OFFSET - .5f * panelSprite->Width(),
 			Screen::Top() + .5f * panelSprite->Height());
 		SpriteShader::Draw(panelSprite, pos);
-		
+
 		WrappedText text(font);
 		text.SetAlignment(Alignment::JUSTIFIED);
 		text.SetWrapWidth(WIDTH - 20);
 		text.Wrap(selectedPlanet->Description());
 		text.Draw(Point(Screen::Right() - X_OFFSET - WIDTH, Screen::Top() + 20), medium);
 	}
-	
+
 	DrawButtons("is ports");
 }
 
@@ -675,24 +664,24 @@ void MapDetailPanel::DrawOrbits()
 	const Sprite *orbitSprite = SpriteSet::Get("ui/orbits and key");
 	SpriteShader::Draw(orbitSprite, Screen::TopRight() + .5 * Point(-orbitSprite->Width(), orbitSprite->Height()));
 	Point orbitCenter = Screen::TopRight() + Point(-120., 160.);
-	
+
 	if(!player.HasVisited(*selectedSystem))
 		return;
-	
+
 	const Font &font = FontSet::Get(14);
-	
+
 	// Figure out what the largest orbit in this system is.
 	double maxDistance = 0.;
 	for(const StellarObject &object : selectedSystem->Objects())
 		maxDistance = max(maxDistance, object.Position().Length() + object.Radius());
-	
+
 	// 2400 -> 120.
 	scale = .03;
 	maxDistance *= scale;
-	
+
 	if(maxDistance > 115.)
 		scale *= 115. / maxDistance;
-	
+
 	// Draw the orbits.
 	static const Color habitColor[7] = {
 		Color(.4, .2, .2, 1.),
@@ -707,7 +696,7 @@ void MapDetailPanel::DrawOrbits()
 	{
 		if(object.Radius() <= 0.)
 			continue;
-		
+
 		Point parentPos;
 		int habit = 5;
 		if(object.Parent() >= 0)
@@ -717,30 +706,30 @@ void MapDetailPanel::DrawOrbits()
 			double warmth = object.Distance() / selectedSystem->HabitableZone();
 			habit = (warmth > .5) + (warmth > .8) + (warmth > 1.2) + (warmth > 2.0);
 		}
-		
+
 		double radius = object.Distance() * scale;
 		RingShader::Draw(orbitCenter + parentPos * scale,
 			radius + .7, radius - .7,
 			habitColor[habit]);
 	}
-	
+
 	// Draw the planets themselves.
 	planets.clear();
 	for(const StellarObject &object : selectedSystem->Objects())
 	{
 		if(object.Radius() <= 0.)
 			continue;
-		
+
 		Point pos = orbitCenter + object.Position() * scale;
 		if(object.HasValidPlanet() && object.GetPlanet()->IsAccessible(player.Flagship()))
 			planets[object.GetPlanet()] = pos;
-		
+
 		const float *rgb = Radar::GetColor(object.RadarType(player.Flagship())).Get();
 		// Darken and saturate the color, and make it opaque.
 		Color color(max(0.f, rgb[0] * 1.2f - .2f), max(0.f, rgb[1] * 1.2f - .2f), max(0.f, rgb[2] * 1.2f - .2f), 1.f);
 		RingShader::Draw(pos, object.Radius() * scale + 1., 0.f, color);
 	}
-	
+
 	// If the player has a pending order for escorts to move to a new system, draw it.
 	if(player.HasEscortDestination())
 	{
@@ -754,7 +743,7 @@ void MapDetailPanel::DrawOrbits()
 			// Use that method below and in Engine for drawing target reticles.
 			auto a = Angle{45.};
 			auto inc = Angle{90.};
-			
+
 			PointerShader::Bind();
 			for(int i = 0; i < 4; ++i)
 			{
@@ -764,14 +753,14 @@ void MapDetailPanel::DrawOrbits()
 			PointerShader::Unbind();
 		}
 	}
-	
+
 	// Draw the selection ring on top of everything else.
 	for(const StellarObject &object : selectedSystem->Objects())
 		if(selectedPlanet && object.GetPlanet() == selectedPlanet)
 			RingShader::Draw(orbitCenter + object.Position() * scale,
 				object.Radius() * scale + 5., object.Radius() * scale + 4.,
 				habitColor[6]);
-	
+
 	// Draw the name of the selected planet.
 	const string &name = selectedPlanet ? selectedPlanet->Name() : selectedSystem->Name();
 	Point namePos(Screen::Right() - 190., Screen::Top() + 7.);
diff --git a/source/MapDetailPanel.h b/source/MapDetailPanel.h
index 9059c53e..e68478f6 100644
--- a/source/MapDetailPanel.h
+++ b/source/MapDetailPanel.h
@@ -38,8 +38,8 @@ public:
 	virtual void Draw() override;
 	// Navigate through the shown planets when there are too many, otherwise use the parent function.
 	virtual bool Scroll(double dx, double dy) override;
-	
-	
+
+
 protected:
 	virtual bool KeyDown(SDL_Keycode key, Uint16 mod, const Command &command, bool isNewPress) override;
 	// Handle single & double-clicks on commodities, planet information, or objects in the "orbits" display.
@@ -60,11 +60,11 @@ private:
 private:
 	int governmentY = 0;
 	int tradeY = 0;
-	
+
 	int planetNbr = 0;
 	double scroll = 0.;
 	double maxScroll = 0.;
-	
+
 	// Default display scaling for orbits within the currently displayed system.
 	double scale = .03;
 

```

</details>

---

**Comment by samrocketman** [comment]
When playing no scrollbar shows up however scrolling definitely does work.  I think this is acceptable (no scrollbar) because in practice it is rare to encounter the need for scrolling planets.

**Review by samrocketman — APPROVED** [review]
Your diff is much smaller with the patch applying format cleanup.

This plays as described and is stable during my play test.

**Comment by Zitchas** [comment]
Tested it out, and it works as described. I did run into a bit of a problem with the scrolling. The scrolling itself works fine, and I like having it (no scroll bar required, in my opinion). However, at certain steps of the scroll the text sometimes extends out the top of the area and/or the bottom of the area. It took a little fiddly scrolling, but I eventually got a screenshot that shows the text overflowing on both the top and bottom.

For reference, this is on a 12560x1440 screen. So the extra height (I assume most people are probably playing on 1080p) might be contributing.

Top and bottom overlflow

File: source/MapDetailPanel.cpp [hunk 5]
```diff
@@ -122,13 +123,33 @@ void MapDetailPanel::Draw()
 
 
 
+bool MapDetailPanel::Scroll(double dx, double dy)
+{
+	Point point = UI::GetMouse();
+	if(maxScroll && point.X() < Screen::Left() + 160 && point.Y() > Screen::Top() + 90
```
Comment (petervdmeer) [inline source/MapDetailPanel.cpp:129]: The values 160 and 90 look like magic numbers that are likely also used in other parts of the code. Can we make such magic numbers named const static variables? (In an appropriate location. maybe in the anonymous namespace?)

File: source/MapDetailPanel.h [hunk 6]
```diff
@@ -59,6 +61,10 @@ class MapDetailPanel : public MapPanel {
 	int governmentY = 0;
 	int tradeY = 0;
 
+	int planetNbr = 0;
```
Comment (petervdmeer) [inline source/MapDetailPanel.h:64]: Please add some clarifying comments to those variables (and maybe also consider if the names are sufficiently descriptive)?

**Review by petervdmeer — CHANGES_REQUESTED** [review]

File: source/MapDetailPanel.cpp [hunk 7]
```diff
@@ -488,57 +533,59 @@ void MapDetailPanel::DrawInfo()
...
+					SpriteShader::Draw(sprite, Point(Screen::Left() + 50, uiPoint.Y()), scale);
+					planetY[planet] = uiPoint.Y() - 65;
+
+					font.Draw({ object.Name(), alignLeft }, uiPoint + Point(0., -52.),
+						planet == selectedPlanet ? medium : dim);
+
+					string reputationLabel = !hasSpaceport			 ? "No Spaceport" :
+						GameData::GetPolitics().HasDominated(planet) ? "Dominated" :
+						planet->GetGovernment()->IsEnemy()			 ? "Hostile" :
+						planet->CanLand()							 ? "Friendly" :
```
Comment (tehhowch) [inline source/MapDetailPanel.cpp:557]: What's going on with your indentation here?

File: source/MapDetailPanel.cpp (hunk 5 above)
Comment (tehhowch) [reply source/MapDetailPanel.cpp:129]: Not to mention 130.

If these magic values are driven by the current pieces of UI being used, they belong in an interfaces.txt specification. You can specify the relative bounds, text positions, pointer positions, static labels, etc. and query them from the code.

**Review by tehhowch — COMMENTED** [review]
Consider creating a new class, e.g. `MapPlanetCard`, which encapsulates this "draw the parameterized display for planet X" logic. It's constructor can cache things like "has an outfitter" and it's draw method can take the current commodity and position information. (Eventually they should be responsible for handling clicks within their bounds, but that may be tough to do while this whole panel is not driven from an interface spec.)

File: source/MapDetailPanel.cpp [hunk 8]
```diff
@@ -12,22 +12,16 @@ PARTICULAR PURPOSE.  See the GNU General Public License for more details.
...
-#include "text/Font.h"
-#include "text/FontSet.h"
-#include "text/Format.h"
+#include "FillShader.h"
 #include "GameData.h"
 #include "Government.h"
-#include "text/layout.hpp"
 #include "MapOutfitterPanel.h"
 #include "MapShipyardPanel.h"
-#include "pi.h"
```
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:30]: It was part of the format cleanup, I'll cancel it, you're right it has no place in this PR

File: source/MapDetailPanel.cpp (hunk 7 above)
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:557]: I guess the code "cleanup" broke some things

File: source/MapDetailPanel.cpp (hunk 5 above)
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:129]: Okay I'll learn how to use the interface.txt for these new values.
Often it comes from image sizes and conventions so it should be easily modifiable by plugins and such.
Those magic numbers where already there when I arrived but may as well add code in a proper way indeed! Also interface.txt can't be that hard to use, I hope

File: source/MapDetailPanel.h [hunk 9]
```diff
@@ -36,6 +36,8 @@ class MapDetailPanel : public MapPanel {
 
 	virtual void Step() override;
 	virtual void Draw() override;
+	// Navigate through the shown planets when there are too many, otherwise use the parent function.
+	virtual bool Scroll(double dx, double dy) override;
```
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapDetailPanel.h:40]: This function is only a few lines long, and needs to know where the mouse is, to know if the scrolling is to be in the planets or in the map. (in the second case it calls the Scroll function of the map)

I could however make a new function that returns a bool to know if it was used or if the Scroll() function from the map needs to be used, but I didn't feel the need for this function to be shorter. That said I'll do it if you want me to (in which case just react with an eye here).

**Comment by Hurleveur** [comment]
> Consider creating a new class, e.g. `MapPlanetCard`, which encapsulates this "draw the parameterized display for planet X" logic. It's constructor can cache things like "has an outfitter" and it's draw method can take the current commodity and position information. (Eventually they should be responsible for handling clicks within their bounds, but that may be tough to do while this whole panel is not driven from an interface spec.)

You mean one of such class for each planet displayed on screen? And I guess such class should use the "magic" values from interfaces.txt
About the handling clicks they would have to be able to communicate well with the rest of the mapDetailPanel, considering you can double click on the "outfitter" place to go into the mapOutfitter, probably using an enum class?

The thing is I don't like creating new classes considering we did not organize everything correctly in folders yet, and yet more classes in this put it all source folder make it harder to understand the whole code when looking at it for the first time. Also this feels like a very small class, but I'll do it still.

**Comment by Hurleveur** [comment]
> Top and bottom overlflow

I'll look into it, managing when the one at the bottom shows or not proved to be a bit tricky for me

File: source/MapDetailPanel.cpp (hunk 5 above)
Comment (Hurleveur) [reply source/MapDetailPanel.cpp]: Okay It's done, but I can only hope I used it the right way

**Comment by tehhowch** [comment]
> > Consider creating a new class, e.g. `MapPlanetCard`, which encapsulates this "draw the parameterized display for planet X" logic. It's constructor can cache things like "has an outfitter" and it's draw method can take the current commodity and position information. (Eventually they should be responsible for handling clicks within their bounds, but that may be tough to do while this whole panel is not driven from an interface spec.)
> 
> You mean one of such class for each planet displayed on screen? And I guess such class should use the "magic" values from interfaces.txt

Yep, created when the selected system is changed

 
> The thing is I don't like creating new classes considering we did not organize everything correctly in folders yet, and yet more classes in this "put it all" source folder make it harder to understand the whole code when looking at it for the first time.

The converse argument is "I couldn't find the class because they were buried in folders whose names I didn't recognize as meaning 'responsible for x'"
That `source/` is a junk drawer for code files used in the build is not an argument against creating classes that have a single responsibility.

> Also this feels like a very small class, ~~but I'll do it still.~~

Small, single-responsibility classes are _desired_, especially if they reduce the complexity of those that consume them.

> edit: thinking more about this, it really feels like unnecessary extra code debt, given we would have to update them all of the time (to select the right category) or even worse ask each one if it was just clicked, unselect all of them when one is clicked...

I'm not sure what you mean by "select the right category" or "unselecting all." The idea behind passing arguments to their "Draw" method is so they know how to highlight the particular pieces of UI they manage (the pointers and text strings), and where to position themselves.

Asking a list of elements, "do you care about this click?" is easier to maintain than the parent iterating through the list; the parent is freed of having intimate knowledge of the layout and also what should happen when a bit of that layout is clicked (consider e.g. the UI - Panel relationship, or ClickZones in the shop panels).

**Comment by Hurleveur** [comment]
This build segfaults when opening the MapDetailPanel, yet all kind of tests (except for macos building because I didnt add the two new files) pass, I think we should add a few more tests.
Also I pushed this unstable version because I can't find where the sefault comes from when opening said MapDetailPanel.

**Comment by quyykk** [comment]
> I can't find where the sefault comes from when opening said MapDetailPanel.

For me it segfaults because `MapPlanetCard.cpp::isSelected` is uninitialized. There might also be something wrong with the Highlight function, I'm not sure because I can't see any planet entries on the map.

**Comment by Hurleveur** [comment]
> > I can't find where the sefault comes from when opening said MapDetailPanel.
> 
> For me it segfaults because `MapPlanetCard.cpp::isSelected` is uninitialized. There might also be something wrong with the Highlight function, I'm not sure because I can't see any planet entries on the map.

Thx! I had no idea something like that (other than a pointer) would cause a segfault.

It was fixed along with a lot of other problems but I need to fix the selection too before pushing changes. (the vector isn't behaving as expected at all)

**Comment by Hurleveur** [comment]
It took me a while but I managed to make the items display partially if there is only space for a part of them.

Normally I only need to restore the actions there where when selecting a category, like if it is outfitter that is selected in the select planet card then select outfitter on map, also there probably was a selection of the planet in the orbit screen, and if you double clicked on the outfitter it would take you there (behaviour which I always found weird, may I not code it back in please?).
Also there is a small weird movement of the trade panel going on, so I'll just make it static at the bottom of the screen (position defined in the interface) and update the sprite, removing the little links with the above part.
I'm thinking of making the government thing draw after the planets so we could have half a planet sprite shown? It just may screw the logic of the uiPoint a bit but it shouldn't matter if I define all positions in the interface.

That said all of those are relatively small code changes that I need some input on what is preferred (thus, reviews), and given they are easy to do if asked, this PR should be review ready now.

**Comment by Zitchas** [comment]
This looks great! Tested in Arculus on both a 1920x1080 and 2556x1440 screen. On the former it makes a list that only displays about 4 planet entries and just the start of a 5th planet, and on the larger screen it fits all 7 planets. It also handles having the window dragged back and forth between the two screens and resizing accordingly.

 The scrolling works nicely with things scrolling on and off the top and bottom of the screen as I expect them to. As in, it acts the same as on website or documents or other scrolling things.

I do note the small jiggle of the commodity price box that Hurleveur mentioned. It's minor enough that I wouldn't mind if this got merged as-is for an unstable release; although it is the sort of thing that I'd hope/expect to be fixed for the following stable release. If it can be nailed down now, all the better.

Thank you for all your work on this! From my player / content-creation perspective, this is looking great and pretty much ready to go.

File: source/MapPlanetCard.cpp [hunk 10]
```diff
@@ -0,0 +1,247 @@
...
+	sprite = object.GetSprite();
+
+	const Interface* planetCardInterface = GameData::Interfaces().Get("map planet card");
+	float planetIconMaxSize = static_cast<float>(planetCardInterface->GetValue("planet icon max size"));
+	spriteScale = min(.5f, min((planetIconMaxSize) / sprite->Width(), (planetIconMaxSize) / sprite->Height()));
+}
+
+
+
+MapPlanetCard::~MapPlanetCard()
```
Comment (Hurleveur) [inline source/MapPlanetCard.cpp:61]: Should I keep this destructor given I dont expect one to remove only one element? (They are meant to be all removed as one)

File: source/MapPlanetCard.cpp [hunk 11]
```diff
@@ -0,0 +1,247 @@
...
+	if(isShown)
+	{
+		const Font &font = FontSet::Get(14);
+		const Color &faint = *GameData::Colors().Get("faint");
+		const Color &dim = *GameData::Colors().Get("dim");
+		const Color &medium = *GameData::Colors().Get("medium");
+		const auto alignLeft = Layout(140, Truncate::BACK);
+
+		const Interface *planetCardInterface = GameData::Interfaces().Get("map planet card");
+		double height = planetCardInterface->GetValue("height");
```
Comment (Hurleveur) [inline source/MapPlanetCard.cpp:126]: I use these values a lot, should they be made static and initiated by the mapdetailpanel?

File: source/MapDetailPanel.cpp [hunk 12]
```diff
@@ -322,6 +336,28 @@ bool MapDetailPanel::RClick(int x, int y)
 
 
 
+void MapDetailPanel::GeneratePlanetCards(const System &system)
+{
+	set<const Planet *> shown{};
+	
+	planetCards.clear();
+	MapPlanetCard::clear();
```
Comment (Hurleveur) [inline source/MapDetailPanel.cpp:344]: I am not sure why I had to do this (clearing manually the list)
I mean I expected the vector clear to delete all elements within it given they are contained in it (that said for optimization this is probably best instead of having each element looking for itself in their private vector when they are deletef in this one)

File: source/MapDetailPanel.cpp [hunk 13]
```diff
@@ -472,73 +530,29 @@ void MapDetailPanel::DrawInfo()
 		PointerShader::Draw(uiPoint + Point(-90., 20.), Point(1., 0.),
```
Comment (Hurleveur) [inline source/MapDetailPanel.cpp:530]: I would like to make the government sprite draw after so planets can be partially hidden by it
It would however completely break the uiPoint thing (I mean all elements will be made constant in position except for the ones in the mapPlanetCards), but I have to make the tradeY constant anyway(as in defined in the interface and not dynamic) so it should not be a problem?

**Review by Hurleveur — COMMENTED** [review]
I am not sure what I should do at those places so I'll open it for discussion

File: source/MapPlanetCard.cpp (hunk 11 above)
Comment (Hurleveur) [reply source/MapPlanetCard.cpp]: I made them static when possible in the functions themselves

File: source/MapDetailPanel.cpp (hunk 13 above)
Comment (Hurleveur) [reply source/MapDetailPanel.cpp]: I made it be drawn after, and I linked the trade sprite position to the end of the planets

**Comment by quyykk** [comment]
Really cool feature! Nice job. Here are two things I noticed (without looking at the code at all):

unlimited planets improvements

Notice how the text is simply offset by a few pixels to the top. The clicking bounds are correct though, it's just the text that is a bit too high.

unlimited planets background example

Notice how there is the white background thing in the current view, while in this PR it's just a solid gray background which is a bit boring. Maybe add them as well? I think it would look better but I'm not that sure so yeah.

**Comment by Hurleveur** [comment]
Thx for the input! I'll easily adjust the text, about the planet sprite it isn't shown because there isn't enough space for it though I should probably adjust it to make it fit 5 planets perfectly in this display (but that's just changing a bit the interface values, should be easy as well, or maybe the checking for space for it is a bit too strict)
I had adjusted those things to look right on my screen but it seems to not work as well for everyone, or maybe I didn't adjust it well enough.

Now about the background lines, sure, I would like to be able to do that but I need the full image else small moons/planets will make it look weird given you will see it is incomplete. Basically the image behind the planets is all I could use, there is not a full circle version available somewhere.

File: source/MapDetailPanel.cpp [hunk 14]
```diff
@@ -283,11 +309,18 @@ bool MapDetailPanel::Click(int x, int y, int clicks)
...
 	}
 
+	const System *const previous = selectedSystem;
 	// The click was not on an interface element, so check if it was on a system.
 	MapPanel::Click(x, y, clicks);
 	// If the system just changed, the selected planet is no longer valid.
 	if(selectedPlanet && !selectedPlanet->IsInSystem(selectedSystem))
 		selectedPlanet = nullptr;
+	// If the system just changed, the planet scroll in the system needs to be reset.
+	if(selectedSystem != previous)
```
Comment (quyykk) [inline source/MapDetailPanel.cpp:319]: Instead of always `GeneratePlanetCards` everywhere, do the same thing MapPanel does: Cache the previous selected system as a data member and then in Step check if the selected system changed.

File: source/MapDetailPanel.cpp [hunk 15]
```diff
@@ -182,13 +211,15 @@ bool MapDetailPanel::KeyDown(SDL_Keycode key, Uint16 mod, const Command &command
...
 			Select(next);
+			GeneratePlanetCards(*selectedSystem);
 		}
 	}
 	else if((key == SDLK_DELETE || key == SDLK_BACKSPACE) && player.HasTravelPlan())
 	{
 		vector<const System *> &plan = player.TravelPlan();
 		plan.erase(plan.begin());
 		Select(plan.empty() ? player.GetSystem() : plan.front());
+		GeneratePlanetCards(*selectedSystem);
```
Comment (quyykk) [inline source/MapDetailPanel.cpp:222]: Did you forget to set the scroll to 0 here? Setting the scroll to 0 should be part of GeneratePlanetCards so it can't be forgotten.

File: source/MapDetailPanel.cpp [hunk 16]
```diff
@@ -322,6 +355,28 @@ bool MapDetailPanel::RClick(int x, int y)
...
+	for(const StellarObject &object : system.Objects())
+		if(object.HasSprite() && object.HasValidPlanet())
+		{
+			// The same "planet" may appear multiple times in one system,
+			// providing multiple landing and departure points (e.g. ringworlds).
+			const Planet *planet = object.GetPlanet();
+			if(planet->IsWormhole() || !planet->IsAccessible(player.Flagship()) || shown.count(planet))
+				continue;
+
+			planetCards.emplace_back(*new MapPlanetCard(object, player.HasVisited(*planet)));
```
Comment (quyykk) [inline source/MapDetailPanel.cpp:373]:
```suggestion
			planetCards.emplace_back(object, player.HasVisited(*planet));
```

Memory leak.

File: source/MapDetailPanel.cpp [hunk 17]
```diff
@@ -322,6 +355,28 @@ bool MapDetailPanel::RClick(int x, int y)
 
 
 
+void MapDetailPanel::GeneratePlanetCards(const System &system)
+{
+	set<const Planet *> shown{};
```
Comment (quyykk) [inline source/MapDetailPanel.cpp:360]:
```suggestion
	set<const Planet *> shown;
```

File: source/MapDetailPanel.cpp (hunk 14 above)
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:319]: But this is what is done here, isn't it? Just that I don't stock it as a member, so maybe it could cause a problem at another place, but the only one that comes to my mind is when the player presses tab in which case the system changes

File: source/MapDetailPanel.cpp (hunk 16 above)
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:373]: I'll change it but could you explain further? You mean that if the planet card isn't create it'll cause a problem?

File: source/MapPlanetCard.cpp [hunk 18]
```diff
@@ -0,0 +1,276 @@
...
+
+
+bool MapPlanetCard::DrawIfFits(const Point &uiPoint)
+{
+	// Need to update this before checking if the element fits.
+	yCoordinate = uiPoint.Y();
+	isShown = Shown();
+	if(isShown)
+	{
+		static const Font &font = FontSet::Get(14);
```
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapPlanetCard.cpp:135]: Okay, I wasn't aware of those plans for the future
Yeah that's why I made them static, caus that way we don't reload them all of the time, will change

File: source/MapPlanetCard.h [hunk 19]
```diff
@@ -0,0 +1,103 @@
...
+	// Return the space available for this planet card on its current position.
+	double AvailableSpace() const;
+
+	const Planet *getPlanet() const;
+
+
+public:
+	static void setScroll(double newScroll);
+	static double getScroll();
+	static void clear();
```
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapPlanetCard.h:61]: Well that's what it was indeed but MapDetailPanel is already so charged
I see what you have in mind, this would cause problems if we had two MapDetailPanels, I'll change it then, but this class accesses it more than said MapDetailPanel, each element looks at it to know where to be drawn

File: source/MapPlanetCard.h [hunk 20]
```diff
@@ -0,0 +1,103 @@
...
+	std::string reputationLabel;
+	const std::string &planetName;
+	// The currently select category (outfitter, shipyard, ...)
+	unsigned selectedCategory = 0;
+
+
+private:
+	static double scroll;
+	// Used so we can give the right number to the planet cards in an internal way.
+	static std::vector<MapPlanetCard *> cards;
```
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapPlanetCard.h:98]: I use it in the destructor as well, but I don't intend anyone to destroy only one panel element so that's why I would even like to destroy that destructor, and I'll make it a value

I don't want to pass it as an index, it means that the one creating this has to know they work with said index, whereas here the class does its own stuff, which I quite like

File: source/MapDetailPanel.cpp [hunk 21]
```diff
@@ -230,35 +261,30 @@ bool MapDetailPanel::Click(int x, int y, int clicks)
...
-						}
-						if(clicks > 1 && SHOW[row] == SHOW_OUTFITTER)
-						{
-							GetUI()->Pop(this);
-							GetUI()->Push(new MapOutfitterPanel(*this, true));
-						}
-					}
-					return true;
+					GetUI()->Pop(this);
+					GetUI()->Push(new MapShipyardPanel(*this, true));
```
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:272]: Yes when we pop the UI, but if we just clicked we need to send it to all the ones after so they unselect themselves

File: source/MapDetailPanel.cpp (hunk 14 above)
Comment (quyykk) [reply source/MapDetailPanel.cpp:319]: This is in `Click`. There are other places where you call GeneratePlanetCards which you can avoid by moving this into Step. If that makes sense.

File: source/MapDetailPanel.cpp (hunk 16 above)
Comment (quyykk) [reply source/MapDetailPanel.cpp]: You're creating a new object with `new` and then copying it into the vector. This newed object needs to be `delete`d manually but since you never do that it creates a memory leak. Hope that makes sense.

File: source/MapPlanetCard.cpp (hunk 18 above)
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapPlanetCard.cpp:135]: You really want me to make the interface data members? 
Each MapPlanetCard has his own? Because this way currently there are only 4 total variables (and static const so they don't get reinstated every time we reload the planetCards)

File: source/MapDetailPanel.cpp (hunk 16 above)
Comment (Hurleveur) [reply source/MapDetailPanel.cpp]: Oh so clearing the vector does not delete all the objects in it if they are in it by value, I thought it did. Thanks!

File: source/MapPlanetCard.h (hunk 19 above)
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapPlanetCard.h:61]: I'll need to make it static though to allow the MapPlanetCards to access it

File: source/MapDetailPanel.cpp (hunk 14 above)
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:319]: Oh, right, so only have it at one place and check if the system was changed, got it!

File: source/MapPlanetCard.h (hunk 20 above)
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapPlanetCard.h]: I did it as you suggested

File: source/MapDetailPanel.cpp [hunk 22]
```diff
@@ -448,102 +507,89 @@ void MapDetailPanel::DrawKey()
...
 void MapDetailPanel::DrawInfo()
 {
-	const Color &faint = *GameData::Colors().Get("faint");
 	const Color &dim = *GameData::Colors().Get("dim");
 	const Color &medium = *GameData::Colors().Get("medium");
 
-	Point uiPoint(Screen::Left() + 100., Screen::Top() + 45.);
+	const Color &back = *GameData::Colors().Get("map side panel background");
+
+	static const Interface *planetCardInterface = GameData::Interfaces().Get("map planet card");
```
Comment (quyykk) [inline source/MapDetailPanel.cpp:515]: Same thing with `static` in this file as well.

File: source/MapDetailPanel.cpp [hunk 23]
```diff
@@ -592,8 +638,8 @@ void MapDetailPanel::DrawInfo()
 	if(selectedPlanet && !selectedPlanet->Description().empty()
 			&& player.HasVisited(*selectedPlanet) && !selectedPlanet->IsWormhole())
 	{
-		static const int X_OFFSET = 240;
-		static const int WIDTH = 500;
```
Comment (quyykk) [inline source/MapDetailPanel.cpp:596]: Unnecessary change.

File: source/MapDetailPanel.cpp [hunk 24]
```diff
@@ -288,6 +321,7 @@ bool MapDetailPanel::Click(int x, int y, int clicks)
 	// If the system just changed, the selected planet is no longer valid.
 	if(selectedPlanet && !selectedPlanet->IsInSystem(selectedSystem))
 		selectedPlanet = nullptr;
+
```
Comment (quyykk) [inline source/MapDetailPanel.cpp:324]: Empty line.

File: source/MapPlanetCard.cpp [hunk 25]
```diff
@@ -0,0 +1,227 @@
...
+	spriteScale = min(.5f, min((planetIconMaxSize) / sprite->Width(), (planetIconMaxSize) / sprite->Height()));
+}
+
+
+
+MapPlanetCard::ClickAction MapPlanetCard::Click(int x, int y, int clicks)
+{
+	ClickAction clickAction = ClickAction::NONE;
+	// The isShown variable should have already updated by the drawing of this item.
+	if(isShown) {
```
Comment (quyykk) [inline source/MapPlanetCard.cpp:62]: Braces belong on a new line.

File: source/MapDetailPanel.cpp (hunk 22 above)
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:515]: I already removed all the inapropriate statics based on what you said
I should just remove all of them and whatever the performance cost? Yeah ik this is the map interface panel it doesn't matter

File: source/MapDetailPanel.cpp (hunk 24 above)
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:324]: Yeah I added it because it adds clarity I think but whatever I don't mind it

**Review by Zitchas — APPROVED** [review]
I can't comment on the code itself; but in practical use this works very nicely. The slight jitter from earlier is gone, it scrolls nicely, and acts the way I would expect it to. 

- [X] It works!
- [X] It looks good!
- [X] It's a feature I really want in-game.
- [X] It has a significant positive impact on future content possibilities

**Review by quyykk — COMMENTED** [review]
Here some general things:

- It is possible to "click-through" the planet cards and change systems if there is a system underneath the panel where you just clicked.
- There's a slight flicker of the planet list when entering the MapDetailPanel
- Should the selected color (of the background) be the same dark shade as in the MapOutfitterPanel and MapShipyardPanel?

File: source/MapDetailPanel.cpp [hunk 26]
```diff
@@ -230,35 +266,32 @@ bool MapDetailPanel::Click(int x, int y, int clicks)
...
-					}
-					return true;
+					GetUI()->Pop(this);
+					GetUI()->Push(new MapOutfitterPanel(*this, true));
+					break;
 				}
+				// Then this is the planet selected.
+				else if(clickAction != MapPlanetCard::ClickAction::NONE)
+				{
+					selectedPlanet = card.GetPlanet();
```
[the remark this answers is not in the document]
Comment (Hurleveur) [reply source/MapDetailPanel.cpp:289]: That's on purpose, I don't want it to break. It needs to still call click on the other planets so they unselect themselves

**Comment by Hurleveur** [comment]
> It is possible to "click-through" the planet cards and change systems if there is a system underneath the panel where you just clicked.

Should be fixed.

> There's a slight flicker of the planet list when entering the MapDetailPanel

I don't notice anything, could you be more specific?

> Should the selected color (of the background) be the same dark shade as in the MapOutfitterPanel and MapShipyardPanel?

I just made it be the same for coherence, I think it should but I'm no UI designer so if anyone has a better looking color/background in mind, please give your ideas!

**Comment by quyykk** [comment]
> I don't notice anything, could you be more specific?

Try going to one of the Remnant systems and then opening the map. If you look at the planet lost you'll see that at the bottom of the list every planet sprite is drawn for like a single frame. This also happens if you are in the MapOutfitterPanel and go to the MapDetailsPanel.

File: data/map.txt [hunk 27]
```diff
@@ -26762,7 +26762,7 @@ planet Ahr
 	outfitter "Coalition Advanced"
 
 planet Aksaray
-	attributes moon "requires: inaccessible" uninhabited
```
Comment (petervdmeer) [inline data/map.txt:26765]: This PR still seems to contain test-data (here and below).

Comment (Hurleveur) [reply data/map.txt:26765]: Well that's the thing this PR fixes precisely so may as well fix it directly instead of forcing Zitchas to do another PR right afterwards.

Comment (Zitchas) [reply data/map.txt:26765]: I'm fine with doing a PR to do this if necessary; but I am also great with it being handled in here.

Comment (quyykk) [reply data/map.txt:26765]: It's helpful to have them in this PR for easy testing.

Comment (petervdmeer) [reply data/map.txt:26765]: Yes, if this change is intentional and desired, then I agree to keep it as part of this PR. (And I should have read the PR text more clearly, it was also properly stated there. :) )

**Review by petervdmeer — APPROVED** [review]
Please do fix the issue reported by quyykk. I didn't see anything strange in the code, so if quyykk is okay with this PR then it is also good to go from me.

**Comment by Hurleveur** [comment]
> Please do fix the issue reported by quyykk. I didn't see anything strange in the code, so if quyykk is okay with this PR then it is also good to go from me.

image
He reported to me the issue was fixed, in PM, however he also mentioned he was trying to change it to improve the UX side of it, so maybe hold off until he gives his official approval.

**Comment by Hurleveur** [comment]
Considering this bug has been existing since 5 years and I think this PR is pretty much merge ready, I think its reasonable to assume we can get it in by 9.1.5, if anyone disagrees do say so and I'll remove the milestone.

**Comment by Zitchas** [comment]
I agree. This has been working solidly for quite a while now, and has just gotten better and more polished in the meantime. Given how it is basically a "blocker" to a fair amount of world-building; and enables more complex systems to be usefully viewed, I think it's a useful fix to push to get into the game at the earliest release we can. This might be particularly important since there's generally talk about 0.9.17 having one or more of our new alien races; which might particularly benefit from this.

As far as that goes, this is already blocking a bit of Remnant world-building, so it could have a positive impact there too.

**Comment by petervdmeer** [comment]
> He reported to me the issue was fixed, in PM, however he also mentioned he was trying to change it to improve the UX side of it, so maybe hold off until he gives his official approval.

We have a lot of PRs ongoing in parallel; those UX improvements can also go to a follow-up PR.
