### PR TITLE
Use the new static runtime to build AppImages

### LINKED ISSUE #7136: Endless Sky will not install or run on Ubuntu 22.04.1 (Jammy)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

_Endless Sky_ v0.9.12 will not install on Ubuntu 22.04.1 (Jammy) from the PPA, because the package depends on _libglew2.1_, and this library is not supported on Jammy. Additionally, the PPA directory for Focal needs to be used, because the directory for Jammy produces an error when polled by _apt_.

The _Endless Sky_ v0.9.12 AppImage will not run on Jammy, because it requires _FUSE_, and this is no longer supported on Jammy, which now uses _FUSE3_.

### Steps to Reproduce

1. Add repository _ppa:mzahniser/endless-sky_ to Jammy installation.
2. Open _Software & Updates_, and change the PPA distribution to _focal_.
3. In a terminal window, run **sudo apt update | sudo apt install endless-sky**.
4. See error... "The following packages have unmet dependencies: endless-sky : Depends: libglew2.1 (>= 1.12.0) but it is not installable."

### Expected Behavior

For the PPA install, the expectation is that _apt_ will automatically install all dependencies from the Ubuntu repositories.

For the AppImage, the expectation is that _FUSE3_ will be used, instead of _FUSE_.

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

Ubuntu 22.04.1 (Jammy Jellyfish)

### Game Source

Other (please describe)

### Game Version

Linux PPA from Launchpad

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by quyykk**
**Bugfix:** This PR fixes #7136

## Fix Details

This uses the new static runtime to build the AppImage, which means that it no longer requires dynamic linking to the ancient unsupported fuse2 library. As such, the AppImage can be run without additional work on newer Ubuntu versions.

It also renames the appdata file to follow the convention: Namely, that it has to be named with the package id.

## Testing Done

Launched the AppImage, it works! It also works on a distro without having to install libfuse2 (Lubuntu 22, as tested by namusetä on Discord).

### CODE REVIEW

File: utils/build_appimage.sh [hunk 1]
```diff
@@ -17,7 +17,15 @@ mv AppDir/usr/share/games/endless-sky/* AppDir/
 
 # Now build the actual AppImage
 curl -sSL https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -o linuxdeploy && chmod +x linuxdeploy
-./linuxdeploy --appdir AppDir -e endless-sky -d endless-sky.desktop -i endless-sky.png --output appimage
+OUTPUT=Endless_Sky-continuous-x86_64.AppImage ./linuxdeploy --appdir AppDir -e endless-sky -d endless-sky.desktop -i endless-sky.png --output appimage
+
+# Use the static runtime for the AppImage. This lets the AppImage being run on systems without fuse2.
+APPTOOL=$(curl -sSL https://github.com/probonopd/go-appimage/releases/expanded_assets/continuous | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
```
Comment (MCOfficer) [inline utils/build_appimage.sh:23]: It's probably better to grep our href specifically instead of relying on it being the first in the list:

```suggestion
APPTOOL=$(curl -sSL https://github.com/probonopd/go-appimage/releases/expanded_assets/continuous | grep -Eo 'href="(/.*?appimagetool-.*-x86_64.AppImage)"' | cut -d '"' -f 2)
```

Also, if we make one further assumption (`gh` being installed), we can do a much less hacky
```
APPTOOL=$(gh release download -R probonopd/go-appimage continuous -p appimagetool*x86_64.AppImage)
```

File: utils/build_appimage.sh [hunk 2]
```diff
@@ -17,7 +17,15 @@ mv AppDir/usr/share/games/endless-sky/* AppDir/
...
+curl -sSL https://github.com$APPTOOL -o appimagetool && chmod +x appimagetool
+
+./Endless_Sky-continuous-x86_64.AppImage --appimage-extract
+chmod -R 755 ./squashfs-root
+./appimagetool ./squashfs-root
```
Comment (MCOfficer) [inline utils/build_appimage.sh]: This is hideous, but I guess it's our only option until linuxdeploy catches up

File: utils/build_appimage.sh [hunk 3]
```diff
@@ -17,7 +17,16 @@ mv AppDir/usr/share/games/endless-sky/* AppDir/
...
+OUTPUT=Endless_Sky-continuous-x86_64.AppImage ./linuxdeploy --appdir AppDir -e endless-sky -d endless-sky.desktop -i endless-sky.png --output appimage
+
+# Use the static runtime for the AppImage. This lets the AppImage being run on systems without fuse2.
+APPTOOL=$(curl -sSL https://github.com/probonopd/go-appimage/releases/expanded_assets/continuous | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
+curl -sSL https://github.com$APPTOOL -o appimagetool && chmod +x appimagetool
+
+./Endless_Sky-continuous-x86_64.AppImage --appimage-extract
+chmod -R 755 ./squashfs-root
+VERSION=000 ./appimagetool ./squashfs-root
+mv ./Endless_Sky-000-x86_64.AppImage $OUTPUT
```
Comment (MCOfficer) [inline utils/build_appimage.sh:29]: This is hideous, but I guess it's our only option until linuxdeploy catches up.

**Review by MCOfficer — COMMENTED** [review]
The "experimental" on the go-appimage repo is a bit offputting, especially since we pull the continuous release...

File: utils/build_appimage.sh (hunk 2 above)
Comment (quyykk) [reply utils/build_appimage.sh]: Until the static runtime is officially blessed yeah unfortunately

**Review by MCOfficer — APPROVED** [review]
