### PR TITLE
Highlight critical messages

### LINKED ISSUE #3361: Mission failure by ship loss is very hard to spot
Imagine you are in a big space battle. Hundreds of ships, thousands of projectiles :boom: :smile:. During all that, it may happen that a mission failure is announced, without sound, in white text at the bottom of the screen. You are going to miss that and later wonder huh, why did the mission fail?

It would be great to improve the visibility of the mission failure message from losing ships; and it should be available after after the fact too.

It's really an awesome game, so thanks a lot for making it.

### PR DESCRIPTION
**Pull request by salqadri**
-----------------------
**Feature:** This PR resolves #3361. Critical messages like mission failures are now highlighted in bright red, and then slowly fade away as other messages do.

## Feature Details
This is achieved by introducing a new importance level, called Highest, and exposing it to the game engine via a new field in the Messages::Entry class. I've also gone ahead and applied it to some messages that I deemed should be highlighted in such a way, such as mission failures. In the process I also took the luxury of adding fixed named colors to the Color class, as I wanted to be able to set the color of the message to `Color::Red`.

## UI Screenshots
MissionFailRed

## Usage Examples
`Messages::Add("Mission failed.", Messages::Importance::Highest);`

## Testing Done
I launched the game, gave myself a mission that spanned the cargo of my combined fleet, went to a pirate system and let some of my escorts be killed and verified that the resulting mission failure message was highlighted Red and faded away without being repeated, and all other non-critical messages remained as they were.

## Performance Impact
N/A

-----

Update: Based on the highest vote in a Poll on Discord, the color has now been set to Orange. Also, I now take the color from the interfaces.txt file so we can easily change this in future. You can even define different colors for each importance level via the interfaces.txt file.

### CODE REVIEW

File: source/Engine.cpp [hunk 1]
```diff
@@ -942,7 +942,13 @@ void Engine::Draw() const
...
 			break;
 		float alpha = (it->step + 1000 - step) * .001f;
-		Color color(alpha, 0.f);
+		Color color;
+		if (it->importance == Messages::Importance::Highest) {
+			color = Color::Red.Additive(alpha);
+		}
+		else {
+			color = Color(alpha);
+		}
```
Comment (Amazinite) [inline source/Engine.cpp:951]: The color used shouldn't be hardcoded, and should instead be defined in the interfaces file as to allow it to be easily customized. (And by extension, we shouldn't be hardcoding any colors into the Color class as you're doing.)
https://github.com/endless-sky/endless-sky/blob/d712e94e3923a81dd1ab14afcc2339ee86790740/data/interfaces.txt#L92-L95

Comment (salqadri) [reply source/Engine.cpp:951]: Ok makes sense, thanks; will update.

Comment (salqadri) [reply source/Engine.cpp]: Done

**Comment by Zitchas** [comment]
I definitely like this idea, and I know that I, personally, would much prefer to have the highest alert level be either bright red or orange. (I'm good either way).

The one caveat is that I would also like there to be alternate options, if possible. Having the critical messages be white, but bold and/or a slightly bigger text size would be very valuable. While I wouldn't use it myself, I know there are people that have a lot of trouble seeing red / shades of red, or can only barely be able to do so. Thus having an alternative that still makes the text stand out but doesn't rely on color to do so would be very helpful in terms of accessibility.

**Comment by salqadri** [comment]
> I definitely like this idea, and I know that I, personally, would much prefer to have the highest alert level be either bright red or orange. (I'm good either way).
> 
> The one caveat is that I would also like there to be alternate options, if possible. Having the critical messages be white, but bold and/or a slightly bigger text size would be very valuable. While I wouldn't use it myself, I know there are people that have a lot of trouble seeing red / shades of red, or can only barely be able to do so. Thus having an alternative that still makes the text stand out but doesn't rely on color to do so would be very helpful in terms of accessibility.
> 

Accessibility is an interesting point that I hadn't considered. Better to tackle that more holistically though in a separate ticket.

**Comment by salqadri** [comment]
Results of poll on the color for critical messages:

image

File: source/Engine.cpp [hunk 2]
```diff
@@ -942,8 +942,23 @@ void Engine::Draw() const
 		if(messagePoint.Y() < messageBox.Top())
 			break;
 		float alpha = (it->step + 1000 - step) * .001f;
-		Color color(alpha, 0.f);
-		messageLine.Draw(messagePoint, color);
+		const Color* color;
```
Comment (tehhowch) [inline source/Engine.cpp:945]: Always initialize pointers:

```suggestion
		const Color *color = nullptr;
```

File: source/Engine.cpp [hunk 3]
```diff
@@ -942,8 +942,23 @@ void Engine::Draw() const
...
+		// This switch will make the compiler force us to handle any new importance levels we add in future
```
Comment (tehhowch) [inline source/Engine.cpp:946]:
```suggestion
```
Unnecessary comment

File: source/Engine.cpp [hunk 4]
```diff
@@ -942,8 +942,23 @@ void Engine::Draw() const
...
+		switch (it->importance) {
+			case Messages::Importance::Highest:
+				color = GameData::Colors().Get("message importance highest");
+				break;
+			case Messages::Importance::High:
+				color = GameData::Colors().Get("message importance high");
+				break;
+			case Messages::Importance::Low:
+				color = GameData::Colors().Get("message importance low");
```
Comment (tehhowch) [inline source/Engine.cpp:955]: if you want to fall back to a default, these should use `.Find` instead of `.Get`, as `Set<T>::Get` will always return a valid pointer.

File: source/Engine.cpp [hunk 5]
```diff
@@ -942,8 +942,23 @@ void Engine::Draw() const
...
+				break;
+		}
+		if (color == nullptr) {
+			color = GameData::Colors().Get("messages importance default"); // Will not be null
+		}
```
Comment (tehhowch) [inline source/Engine.cpp:960]: Typo + styleguide corrections:
```suggestion
		if(!color)
			color = GameData::Colors().Get("message importance default");
```

**Review by tehhowch — CHANGES_REQUESTED** [review]

File: source/Engine.cpp (hunk 2 above)
Comment (salqadri) [reply source/Engine.cpp]: Done.

File: source/Engine.cpp (hunk 3 above)
Comment (salqadri) [reply source/Engine.cpp]: Done.

File: source/Engine.cpp (hunk 4 above)
Comment (salqadri) [reply source/Engine.cpp]: Done.

File: source/Engine.cpp (hunk 5 above)
Comment (salqadri) [reply source/Engine.cpp]: Done.

**Comment by bluss** [comment]
Thanks for fixing this! Would it make sense for these to fade slower than regular messages?

**Comment by Zitchas** [comment]
Probably a little bit, yes.

**Comment by tehhowch** [comment]
> Thanks for fixing this! Would it make sense for these to fade slower than regular messages?

@bluss @Zitchas

That's better addressed in a different manner, e.g. https://github.com/endless-sky/endless-sky/issues/4794
