### PR TITLE
Fix plugins with a custom name

### LINKED ISSUE #9237: Plugins with a custom name in `plugin.txt` are always displayed as enabled.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Plugins with a custom name in `plugin.txt` are always displayed as enabled. **They can be disabled**, but they are **displayed as enabled**.

Additionally, the content of `plugins.txt` (not the file in the plugin, the file listing enabled plugins) does not look right, because it have an entry for both the plugin folder and the plugin name.

### Steps to Reproduce

1. Install a plugin in a folder:
  - The plugin must define a custom name in `plugin.txt`
  - The folder name of the plugin must be different
  - [This is the plugin I tested with](https://github.com/Pshy0/es-empty-plugin), put it in a `es-empty-plugin` folder.
2. Launch the game and try enabling / disabling the plugin: it stays checked.

### Expected Behavior

Disabled plugins should not be displayed as enabled.

### Screenshots

- Initial state:
image
- Clicking the checkbox (game knows it needs to reload but the checkbox didnt update appropriately):
image
- Current plugins state:
image
- After closing the game:
image

Note that `Ruin The Sky` is also supposed to be disabled here, but is displayed as enabled.

### Link to save file

_No response_

### Operating System

Ubuntu 23.04

### Game Source

GitHub Releases

### Game Version

7c815e1a7ab84a847df227d907d046afa562e20b (continuous)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by quyykk**
**Bugfix:** This PR fixes #9237

## Fix Details

Plugins with a custom name where saved under the folder name, instead of of the custom name. This PR fixes this by properly storing the plugin with its custom name in the plugins set.

## Testing Done

Tested with the steps described in the linked issue, which are fixed with this PR.

### CODE REVIEW

**Comment by Amazinite** [comment]
Notably, folder names need to be unique as enforced by the OS, but now there's nothing stopping two plugins from having the same name in their metadata file. We should probably warn if a conflict occurs, and let it be first-come-first-serve where the first plugin that loads gets the name from its metadata, but all subsequent plugins with the same name in their metadata go by the folder name.

**Comment by warp-core** [comment]
Since there are two plugin folders, the plugin folder names might not actually be unique, only the paths are guaranteed to be unique.

**Comment by quyykk** [comment]
I've made it so that plugin names are fully first-come-first-serve. Any plugin with the same name doesn't get loaded at all, on the assumption that it is the same plugin (or older/newer) and thus loading it again is not a good idea.

**Review by Pshy0 — COMMENTED** [review]
This PR does not load my plugins anymore except the one that is in double (I tested by adding two plugin `es-demo-plugin-v1` and `es-demo-plugin-v2` buth renamed `Demo Plugin` in their `plugin.txt`).
image

**Comment by quyykk** [comment]
Whoops, the one time I don't test my change lol. Should be fixed now, thanks!

**Review by Pshy0 — COMMENTED** [review]
Plugins now load and are correctly displayed as being enabled or disabled.

When I disable `Empty Plugin`:
image
The condition `installed plugin: es-empty-plugin` is set while `installed plugin: Empty Plugin` is not. Is this intended?

This is the states you get with two plugins having the name of the folder of the other:
image
Here all demo plugins are disabled. I used this data to see what conditions are set:
```
mission "Plugin Test"
	landing
	repeat
	on offer
		conversation
			`tests:`
			`	has "installed plugin: Empty Plugin"`
				to display
					has "installed plugin: Empty Plugin"
			`	has "installed plugin: es-empty-plugin"`
				to display
					has "installed plugin: es-empty-plugin"
			`	has "installed plugin: Demo Plugin"`
				to display
					has "installed plugin: Demo Plugin"
			`	has "installed plugin: es-demo-plugin-v1"`
				to display
					has "installed plugin: es-demo-plugin-v1"
			`	has "installed plugin: es-demo-plugin-v2"`
				to display
					has "installed plugin: es-demo-plugin-v2"
```
image

If a player who do not knows about logs installs different versions of the same plugin in different folders (for updating it), and because the folder `plugin-v1` will be loaded before `plugin-v2`, they are possibly going to have a hard time troubleshooting their mistake. Log warnings are good for dev mistakes, not for user mistakes. Should there be something more obvious like a red warning next to the plugin name or in it's description, or a popup?

**Comment by quyykk** [comment]
> The condition `installed plugin: es-empty-plugin` is set while `installed plugin: Empty Plugin` is not. Is this intended?

No that's another bug. I'll fix it.

>  Should there be something more obvious like a red warning next to the plugin name or in it's description, or a popup?

That's a good point, I'm not sure what the best way to warn the user though.. hmmmm

File: source/Plugins.cpp [hunk 1]
```diff
@@ -59,42 +59,50 @@ bool Plugin::IsValid() const
...
+			+ "\" because another plugin with the same name has already been loaded");
+		return nullptr;
 	}
-	// Set values from old about.txt files.
-	if(plugin->aboutText.empty())
-		plugin->aboutText = Files::Read(path + "about.txt");
 
+	if(!plugin)
+		plugin = plugins.Get(name);
+	plugin->name = std::move(name);
```
Comment (warp-core) [inline source/Plugins.cpp:102]: Why not just use "Get" in the first place?
Even if it does insert a new item into the collection, that will still return `false` to IsValid.

File: source/Plugins.cpp [hunk 2]
```diff
@@ -59,42 +59,48 @@ bool Plugin::IsValid() const
...
 	}
 
-	// Set missing required values.
-	if(plugin->name.empty())
+	// 'name' is a required field for plugins with a plugin description file.
+	if(Files::Exists(pluginFile) && !hasName)
+		Logger::LogError("Warning: Missing required \"name\" field inside plugin.txt");
+
+	// Plugin names should be unique.
+	auto *plugin = plugins.Get(name);
```
Comment (warp-core) [inline source/Plugins.cpp:92]: What about the case where a plugin doesn't have a `plugins.txt` file?
Shouldn't you be assigning the folder name to `name`? It seems like you're searching `plugins` with an empty string otherwise.

Comment (quyykk) [reply source/Plugins.cpp:92]: The default value of `name` is the folder name yes

File: source/Plugins.cpp [hunk 3]
```diff
@@ -59,42 +59,48 @@ bool Plugin::IsValid() const
...
+	if(plugin && plugin->IsValid())
 	{
-		plugin->name = std::move(name);
-		if(Files::Exists(pluginFile))
-		{
-			Logger::LogError(
-				"Failed to find name field in plugin.txt. Defaulting plugin name to folder name: \"" + plugin->name + "\"");
-		}
+		Logger::LogError("Warning: Skipping plugin located at \"" + path
+			+ "\" because another plugin with the same name has already been loaded");
```
Comment (warp-core) [inline source/Plugins.cpp:96]:
```suggestion
			+ "\" because another plugin with the same name has already been loaded from: \""
			+ plugin->path + "\".");
```

**Comment by warp-core** [comment]
Should invalid plugins (ones that were attempting to use a name that is already used) be skipped in `Plugins::Save`?

**Comment by quyykk** [comment]
nice catch, fixed
