### PR TITLE
Play landing sound when starting the game with no recent pilot.

### LINKED ISSUE #6635: Launching the game without a pilot loaded doesn't play docking sound
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If the game launches and there isn't a pilot loaded, the "docking" sound won't play after loading finishes.

### Steps to Reproduce

1. Load a pilot
2. Delete the pilot
3. Restart the game

### Expected Behavior

There shouldn't be any inconsistencies in when the landing sound plays and doesn't on the main menu.

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

Windows 10

### Game Source

Built from source

### Game Version

9c3d02cc143848574546143ce45e6d412e3e8e69

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by quyykk**
**Bugfix:** This PR fixes #6635 

## Fix Details

Plays the landing sound if no recent save file was loaded.

## Testing Done

Started the game with no save file: On master silence, with this PR you can hear the landing sound.

### CODE REVIEW

File: source/GameLoadingPanel.cpp [hunk 1]
```diff
@@ -58,7 +58,10 @@ void GameLoadingPanel::Step()
 		// Set the game's initial internal state.
 		GameData::FinishLoading();
 
-		player.LoadRecent();
+		// Load the last loaded save file. If there is none then play the default landing sound.
+		// (If a save file is loaded then the same sound is played when loading it).
+		if(!player.LoadRecent())
+			Audio::Play(Audio::Get("landing"));
```
Comment (tehhowch) [inline source/GameLoadingPanel.cpp:65]: Per comments in the linked issue, add a TODO comment for reverting this change when implementing sounds & music in the loading phase / animation panel.
