### PR TITLE
fix(bug): Fix crash during wormhole link generation

### LINKED ISSUE #10328: endless sky seems to crash with too many systems  even with large amounts of free memory?
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

endless sky crashes with many plugins adding new systems

### Steps to Reproduce

install plugins adding custom thumbnails and then install as many plugins adding custom systems as you need to crash , then remove custom thumbnail plugins  (or resize all images in it to be 50% scale), it should still crash confirming that it is not a OOM

### Expected Behavior

let me eat as many plugins as i need to until memory is consumed or my thirst for missions is quelched

### Screenshots

not a screenshot but here to confirm not OOM
https://github.com/user-attachments/assets/e493001c-200e-4d66-be04-85d485ff0977

### Link to save file

not applicable but here anyway
[c56 c56.txt](https://github.com/user-attachments/files/16301516/c56.c56.txt)

### Operating System

 Nyarch Linux x86_64 

### Game Source

Other (please describe)

### Game Version

0.10.8-1

### Additional Information

got it from distro package manager

### PR DESCRIPTION
**Pull request by tibetiroka**
**Bug fix**

Fixes a bug that can cause crashes during wormhole link generation with missing systems. Fixes #10328.

## Summary
I ran the game with the sanitizers, and they told me where the crash was:
```
endless-sky/source/Wormhole.cpp:242:58: runtime error: member access within null pointer of type 'const struct StellarObject'
endless-sky/source/Wormhole.cpp:242:58: runtime error: member call on null pointer of type 'const struct Body'
endless-sky/source/Body.cpp:66:9: runtime error: member access within null pointer of type 'const struct Body'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==9471==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000060 (pc 0x5a96d3b7d29d bp 0x7321333fe700 sp 0x7321333fe6f0 T7)
==9471==The signal is caused by a READ memory access.
==9471==Hint: address points to the zero page.
    #0 0x5a96d3b7d29d in Body::GetSprite() const endless-sky/source/Body.cpp:66
    #1 0x5a96d4ce29f0 in Wormhole::GenerateLinks() endless-sky/source/Wormhole.cpp:242
    #2 0x5a96d4ce0e0a in Wormhole::LoadFromPlanet(Planet const&) endless-sky/source/Wormhole.cpp:137
    #3 0x5a96d4654b83 in Planet::FinishLoading(Set<Wormhole>&) endless-sky/source/Planet.cpp:301
    #4 0x5a96d4c7c7ae in UniverseObjects::FinishLoading()endless-sky/source/UniverseObjects.cpp:87
    #5 0x5a96d4c7bbaf in operator() endless-sky/source/UniverseObjects.cpp:70
    #6 0x5a96d4c932aa in __invoke_impl<void, UniverseObjects::Load(TaskQueue&, const std::vector<std::__cxx11::basic_string<char> >&, bool)::<lambda()>&> /usr/include/c++/14.1.1/bits/invoke.h:61
    #7 0x5a96d4c92664 in __invoke_r<void, UniverseObjects::Load(TaskQueue&, const std::vector<std::__cxx11::basic_string<char> >&, bool)::<lambda()>&> /usr/include/c++/14.1.1/bits/invoke.h:111
    #8 0x5a96d4c9185c in _M_invoke /usr/include/c++/14.1.1/bits/std_function.h:290
    #9 0x5a96d3d86a40 in std::function<void ()>::operator()() const /usr/include/c++/14.1.1/bits/std_function.h:591
    #10 0x5a96d4be3a5f in TaskQueue::ThreadLoop() endless-sky/source/TaskQueue.cpp:151
    #11 0x5a96d4c05d0a in void std::__invoke_impl<void, void (*)() noexcept>(std::__invoke_other, void (*&&)() noexcept) /usr/include/c++/14.1.1/bits/invoke.h:61
    #12 0x5a96d4c05c5f in std::__invoke_result<void (*)() noexcept>::type std::__invoke<void (*)() noexcept>(void (*&&)() noexcept) /usr/include/c++/14.1.1/bits/invoke.h:96
    #13 0x5a96d4c05a2f in void std::thread::_Invoker<std::tuple<void (*)() noexcept> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/14.1.1/bits/std_thread.h:292
    #14 0x5a96d4c0594b in std::thread::_Invoker<std::tuple<void (*)() noexcept> >::operator()() /usr/include/c++/14.1.1/bits/std_thread.h:299
    #15 0x5a96d4c058cd in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)() noexcept> > >::_M_run() /usr/include/c++/14.1.1/bits/std_thread.h:244
    #16 0x73213d2e0c83 in execute_native_thread_routine /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:104
    #17 0x73213da5cc79 in asan_thread_start /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_interceptors.cpp:234
    #18 0x73213c8a6dec  (/usr/lib/libc.so.6+0x92dec) (BuildId: 32a656aa5562eece8c59a585f5eacd6cf5e2307b)
    #19 0x73213c92a0db  (/usr/lib/libc.so.6+0x1160db) (BuildId: 32a656aa5562eece8c59a585f5eacd6cf5e2307b)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV endless-sky/source/Body.cpp:66 in Body::GetSprite() const
Thread T7 created by T0 here:
    #0 0x73213daf38fb in pthread_create /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_interceptors.cpp:245
    #1 0x73213d2e0d81 in __gthread_create /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:676
    #2 0x73213d2e0d81 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:172
    #3 0x5a96d4bed4ff in std::thread::thread<void (*)() noexcept, , void>(void (*&&)() noexcept) (/mnt/Speed/GitHub/endless-sky/build/linux/Debug/endless-sky+0x537f4ff) (BuildId: e02afcec07c1f1bd99f5891e4657eba2ea6eee4a)
    #4 0x5a96d4be1f4d in WorkerThreads /home/user/Documents/GitHub/endless-sky/source/TaskQueue.cpp:39
    #5 0x5a96d4be520c in __static_initialization_and_destruction_0 /home/user/Documents/GitHub/endless-sky/source/TaskQueue.cpp:53
    #6 0x5a96d4be524a in _GLOBAL__sub_I__ZN9TaskQueueD2Ev /home/user/Documents/GitHub/endless-sky/source/TaskQueue.cpp:181
    #7 0x73213c839dc3 in __libc_start_main (/usr/lib/libc.so.6+0x25dc3) (BuildId: 32a656aa5562eece8c59a585f5eacd6cf5e2307b)
    #8 0x5a96d38c2584 in _start (/mnt/Speed/GitHub/endless-sky/build/linux/Debug/endless-sky+0x4054584) (BuildId: e02afcec07c1f1bd99f5891e4657eba2ea6eee4a)

==9471==ABORTING
```

## Testing Done
I tested that the game no longer crashes.

## Save File
See the attached issue for the save file and plugins.

### CODE REVIEW

**Review by RisingLeaf — APPROVED** [review]

**Review by TomGoodIdea — APPROVED** [review]

**Comment by warp-core** [comment]
Does this mean that it's possible for a Planet to believe it is in a System that it actually has no stellar object in?
That seems like it's likely to cause problems elsewhere if it is.

**Comment by tibetiroka** [comment]
I thought it was specific to wormholes as they have some custom handling, but I haven't checked extensively.

How would such a planet be defined?

File: source/System.cpp [hunk 1]
```diff
@@ -167,7 +167,7 @@ void System::Load(const DataNode &node, Set<Planet> &planets)
 				// that they are no longer here.
 				for(StellarObject &object : objects)
 					if(object.GetPlanet())
-						planets.Get(object.GetPlanet()->TrueName())->RemoveSystem(this);
+						object.GetPlanet()->RemoveSystem(this);
```
Comment (RisingLeaf) [inline source/System.cpp:170]: system is already friend, do we need a getter?

Comment (tibetiroka) [reply source/System.cpp:170]: `planet` was a const pointer. I suppose I could leave it as non-const member without a non-const getter, but I'm not sure if that's a better solution.

Comment (TomGoodIdea) [reply source/System.cpp:170]: If the non-const getter is used only here, in a place where we can access private members directly, I don't think it's necessary

Comment (RisingLeaf) [reply source/System.cpp:170]: agreed with tom

**Comment by tibetiroka** [comment]
> if(object.GetPlanet() && planets.Get(object.GetPlanet()->TrueName()))
	planets.Get(object.GetPlanet()->TrueName())->RemoveSystem(this);

That wouldn't remove the system from the planet with it has no true name, which was causing the bug.

**Comment by RisingLeaf** [comment]
ah nvm then

**Review by TomGoodIdea — APPROVED** [review]

**Comment by warp-core** [comment]
Thoughts on just using `const_cast`? We already have non-const access to the collection where the object is stored, we just need to find the object in there. I don't think I like StellarObject retaining a non-const pointer forever.
@tehhowch if you're available for comment?

**Comment by warp-core** [comment]
> I agree with the sentiment of not wanting to store planet as non const, but const_cast ? this would be very prone to undefined behaviour in the future as well as just going against the meaning of const. Instead it might make more sense to find a way to retrieve the non const pointer to the object from somewhere else

We can traverse the entire collection and compare addresses in the case of the planet not being defined. It's probably not the nicest looking solution, and it'll cost some performance (though, this should be a very, very rare case, and this will be during loading so not super performance sensitive, and as commparisons go, pointer comparisons are fairly fast) but it's probably the safest option.

**Comment by RisingLeaf** [comment]
I would definitely prefer that over a const_cast

File: source/System.cpp [hunk 2]
```diff
@@ -167,7 +167,7 @@ void System::Load(const DataNode &node, Set<Planet> &planets)
 				// that they are no longer here.
```
Comment (warp-core) [inline source/System.cpp:167]:
```suggestion
				// that they are no longer here.
				// Use const_cast to convert the "const Planet *" to "Planet *".
				// Non-const access is available through the passed parameter "Set<Planet> &planets"
				// but, in the case of an as-yet undefined Planet, the object will not have a name with which
				// it can be found in that collection.
```
