### PR TITLE
Fix algebra error in scan formula and replace 2s minimum scan time with exponential dropoff

### LINKED ISSUE #9201: The scan speed cap feels unintuitive (and is too easy to hit)
### Problem Description

I was looking at #8231 to see if after the merging of #8288 whether the added number of scanners was overkill. Instead of downgrading the LP144a to a single LP072a, I downgraded to an LP072 and an LP036a, providing only 10 extra tons for scanners. With this, I bought 4 outfit scanners and 2 cargo scanners, bringing the Gunboat's total to 5 and 3. I then scanned a Carrier and observed that the scan speeds were the same. Thinking it might've just been a coincidence in the ratios between the scan speeds and the Carrier's size, I added 10 more outfit scanners but kept the number of cargo scanners at 3. The scan speeds were still the same. Turns out I'm hitting the scan speed cap, and it only took a relatively small number of scanners to hit it. So I decided to lower the number of outfit scanners while keeping the number of cargo scanners the same to see how few outfit scanners I needed to hit the speed cap (using the speed capped cargo scanners as a frame of reference). With only a single outfit scanner I was hitting the scan speed cap when scanning a Carrier.

Not only does it seem unintuitive to me that adding more scanner wouldn't improve your scan performance due to this cap, the cap also seems far too easy to hit.

### Related Issue Links

#8288 caused the scan speed to be a minimum 2 seconds. No matter how many scanners you have, you can't get any faster.

### Desired Solution

Instead of the cap being a hard cutoff, having it be something that is approached with more scanners being added. Generally, the way things are balanced in Endless Sky is either they provide a flat benefit (most things), or they provide diminishing returns (such as with ramscoops). Rarely if ever is there a hard cutoff beyond which a higher attribute value provides no benefit. If the diminishing returns are great enough, then the hard cap could be only a single frame, with that cap just never being reached in practice.

### Alternative Approaches

Just go back to the drawing board again for scanning. ¯\\\_(ツ)_/¯

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by UnorderedSigh**
**Content (Artwork / Missions / Jobs)**
Fixes #9201 wherein @Amazinite didn't like having a minimum scan time and @ziproot discovered a big math error.

## Summary

There are two problems with the Ship::Scan logic right now. An algebra error and a 2 second minimum scan time.

### Math Error

The first is a big math error here described by @ziproot 

> EDIT: I just tested with 10 million scan power. That took two seconds. So it seems like the scan speed cap is too hard to hit.

Two constants were wrong in Ship.cpp because of an algebra error.

When deriving the scaling factor formula, I inverted the scan formula incorrectly.

This:
`       // factor = pow(sqrt(scanEfficiency) * framesToFullScan / SCAN_TIME, 1.5) / referenceSize`

Should be this:
`       // factor = pow(sqrt(scanEfficiency) * framesToFullScan / SCAN_TIME, -1.5) / referenceSize`

(Notice the `-`)

If you correct that in Ship.cpp by recalculating the constants, the scan rates are correct: 3-10 seconds for a gunship to scan a human ship.

```diff
-       const double SCAN_CARGO_FACTOR = 3;
+       const double SCAN_CARGO_FACTOR = pow(1.0 / sqrt(5), -1.5) / 600;
-       const double SCAN_OUTFIT_FACTOR = 10;
+       const double SCAN_OUTFIT_FACTOR = pow(1.0 / sqrt(15), -1.5) / 740;
```

### Exponential Drop-Off Instead of a Hard Cap

However, @Amazinite doesn't like the idea of a minimum scan time at all. Instead, I'm replacing it with an exponential dropoff in scan rate. I'm using the brownish-yellow color here, which is an exponent of 5.

ScanDropoff

### Free Worlds Scanning Mission

@Pointedstick's test save from #7640 has a scanner-equipped Splinter at the "go scan that Cruiser" mission in the Free Worlds campaign. The mission is doable with one scanner, and easy with three.

[Morgan.Atrasco.txt](https://github.com/endless-sky/endless-sky/files/10549443/Morgan.Atrasco.txt)

### Illegal Missions

Here's another one from @movingpictures: a Heavy Shuttle up to no good, flying through *heavily* patrolled space:

[Lenny.Lightfingers](https://github.com/endless-sky/endless-sky/files/10611805/Lenny.Lightfingers.txt)

Here's four from me: Sparrow, Heavy Shuttle, Clipper, and Blackbird, outfitted for smuggling, all with illegal missions through well-patrolled space, and you don't have enough fuel to reach the destination.

[Aimet Taepip~3029-04-20 Sparrow Test.txt](https://github.com/endless-sky/endless-sky/files/10611903/Aimet.Taepip.3029-04-20.Sparrow.Test.txt)
[Aimet Taepip~3029-04-18 Heavy Shuttle Test.txt](https://github.com/endless-sky/endless-sky/files/10611902/Aimet.Taepip.3029-04-18.Heavy.Shuttle.Test.txt)
[Aimet Taepip~3029-04-18 Clipper Test.txt](https://github.com/endless-sky/endless-sky/files/10611904/Aimet.Taepip.3029-04-18.Clipper.Test.txt)
[Aimet Taepip~3029-04-18 Blackbird Test.txt](https://github.com/endless-sky/endless-sky/files/10611905/Aimet.Taepip.3029-04-18.Blackbird.Test.txt)

### Big Ship Illegal Mission and AI Bugs

[Aimet Taepip~3029-04-19 Ranoerek Test.txt](https://github.com/endless-sky/endless-sky/files/10614015/Aimet.Taepip.3029-04-19.Ranoerek.Test.txt)

It generally takes the full ten seconds to scan my Ranoerek.

### CODE REVIEW

**Comment by UnorderedSigh** [comment]
If #9551 is merged, then the formulae must be updated again:

- sqrt(5) => sqrt(500)
- sqrt(15) => sqrt(1500)

**Review by Quantumshark — APPROVED** [review]

**Comment by ziproot** [comment]
Um, now scanning is too powerful.
image

**Review by ziproot — APPROVED** [review]

**Comment by ziproot** [comment]
I have tested using your build and the provided save files, and everything appears to take as long as it should.

File: source/Ship.cpp [hunk 1]
```diff
@@ -64,31 +64,32 @@ namespace {
...
+	// with an exponent of SCAN_DROPOFF_EXPONENT.
+	const double LINEAR_RATE = 5;
+	const double SCAN_DROPOFF_EXPONENT = 5;
 
 	// These numbers ensure it takes 10 seconds for a Cargo Scanner to scan
 	// a Bulk Freighter at point blank range. Any ship with less than 40
 	// cargo space takes as long as a ship with 40 cargo space.
 	const double SCAN_MIN_CARGO_SPACE = 40;
-	const double SCAN_CARGO_FACTOR = 3;
+	const double SCAN_CARGO_FACTOR = pow(1.0 / sqrt(5), -1.5) / 600;
```
Comment (quyykk) [inline source/Ship.cpp:83]: This can be simplified. Although, it might be a good idea to calculate the final value directly and use that instead.

Comment (UnorderedSigh) [reply source/Ship.cpp:83]: No, no, definitely not. That's how I messed it up before. With the numbers present, you see: 5=cargo scanner, 600=bulk freighter size. Then you compare it to the formula a few lines down and you know you got it right.

**Comment by UnorderedSigh** [comment]
> ~Um, now scanning is too powerful.~ image EDIT: I'm stupid. Ignore this.

Hai space is why I made a 2 second minimum scan time. Now a big ship will have maybe 1-2 seconds, and small ships are doomed. I could start the exponential drop-off at 4 seconds instead of 2, but then players won't be able to insta-scan enemies.

For tuning scanners, we need to focus only on human space before or during the main campaign. Anywhere else aliens can scan you, that scanning isn't for of missions or jobs yet. It's just present for lore reasons. Once we know standard human scanners work well, we can move on to balancing alien scanners.

Surely, hiding illegal goods from more advanced races will require more advanced techniques than a large cargo hold.

**Comment by ziproot** [comment]
By "I'm stupid" I meant "I forgot to disable my plugin which had the workaround of multiplying scan efficiency by 100" so the Hai scanners were more powerful than they should have been.
On the other hand, I'm not sure if Amazinite was really stuck at 10 seconds because of the algebra error or if they were really hitting the hard cap almost immediately.

**Comment by UnorderedSigh** [comment]
> By "I'm stupid" I meant "I forgot to disable my plugin which had the workaround of multiplying scan efficiency by 100" so the Hai scanners were more powerful than they should have been. On the other hand, I'm not sure if Amazinite was really stuck at 10 seconds because of the algebra error or if they were really hitting the hard cap almost immediately.

It was the algebra error.

**Comment by ziproot** [comment]
In that case, wouldn't #9201 be addressed simply by fixing the algebra error?

**Comment by UnorderedSigh** [comment]
> In that case, wouldn't #9201 be addressed simply by fixing the algebra error?

No, people also want to insta-scan AI ships by packing massive piles of scanners. Read through the comments and you'll see such a discussion.

File: source/Ship.cpp [hunk 2]
```diff
@@ -64,31 +64,32 @@ namespace {
...
 	// This ensures it takes 10 seconds for an Outfit Scanner to scan a
 	// Bactrian at point blank range. Any ship with less than 200 outfit
 	// space takes as long as a ship with 200 outfit space.
 	const double SCAN_MIN_OUTFIT_SPACE = 200;
-	const double SCAN_OUTFIT_FACTOR = 10;
+	const double SCAN_OUTFIT_FACTOR = pow(1.0 / sqrt(15), -1.5) / 740;
 
 	// Formula for the scan outfit or cargo factor is:
-	// factor = pow(sqrt(scanEfficiency) * framesToFullScan / SCAN_TIME, 1.5) / referenceSize
+	// factor = pow(sqrt(scanEfficiency) * framesToFullScan / SCAN_TIME, -1.5) / referenceSize
```
Comment (quyykk) [inline source/Ship.cpp:92]: comments usually appear first, and not last. I'd say move this up

File: source/Ship.cpp (hunk 1 above)
Comment (quyykk) [reply source/Ship.cpp:83]: IMO if you add a comment saying which formula was used I think that would be enough. There's really no need to calculate this value at runtime.

**Comment by UnorderedSigh** [comment]
> IMO if you add a comment saying which formula was used I think that would be enough. There's really no need to calculate this value at runtime.
It's calculated once, at compile time. 

Keeping the calculation in the code, and the formula next to it, let's the reader know what was done and why. When it comes time to tweak things, you can change the relevant part of the calculation instead of figuring it out a second time.

**Comment by quyykk** [comment]
> Keeping the calculation in the code, and the formula next to it, let's the reader know what was done and why. When it comes time to tweak things, you can change the relevant part of the calculation instead of figuring it out a second time.

That's why you have the comment with the formula though? What's there to figure out?

File: source/Ship.cpp (hunk 2 above)
Comment (UnorderedSigh) [reply source/Ship.cpp]: I rearranged the comments. Does it make more sense now?

File: source/Ship.cpp (hunk 1 above)
Comment (UnorderedSigh) [reply source/Ship.cpp:87]: I've rearranged the comments so it makes more sense. How does it look now?

**Comment by UnorderedSigh** [comment]
Your scan times will be dangerously low in Hai space unless you use these:

https://github.com/endless-sky/endless-sky/pull/9562

File: source/Ship.cpp (hunk 1 above)
Comment (thewierdnut) [reply source/Ship.cpp:87]: > There's really no need to calculate this value at runtime.

It won't be. The compiler will evaluate this at compile time. 

https://godbolt.org/z/qbva75sbe

Comment (UnorderedSigh) [reply source/Ship.cpp:87]: I think it's one of those things where the compiler isn't *required* to optimize it away, so you're a slave to the optimization heuristics. Maybe there's another way to express it that would force MSVC to optimize it away?

Comment (UnorderedSigh) [reply source/Ship.cpp:87]: Even if I make it a static const, MSVC won't optimize it away. I am unimpressed.

Comment (UnorderedSigh) [reply source/Ship.cpp:87]: I see this, but the workaround doesn't work in Compiler Explorer, even with /fp:fast

https://developercommunity.visualstudio.com/t/MSVC-compiler-doesnt-optimize-powx2/10347300?q=%22task+runner%22+gulp+duration&sort=newest

Comment (warp-core) [reply source/Ship.cpp:87]: Using `constexpr` instead of `const` should guarantee evaluation at compile time, if that's a concern.
I agree with using the full expression instead of evaluating it ourselves and just having a single literal here. It's much more informative than a single value would be, especially with the context of the actual scanning process. And it makes errors in this value easier to spot.
The only drawback I think is that the actual value is not immediately clear when reading it, you'd have to evaluate it yourself, but if it is a `constexpr`, and IDE should be able to tell you what it is anyway.

Comment (UnorderedSigh) [reply source/Ship.cpp:87]: With constexpr, I get an error at compile time since pow and sqrt are not constexpr.

Comment (thewierdnut) [reply source/Ship.cpp:87]: The full expression is only executed once at startup, and only takes 14 ns to run on my computer. I see no real reason to have the pre-computed value in the code.

Comment (UnorderedSigh) [reply source/Ship.cpp:87]: From my reading of the assembly language, MSVC only calculates it once at runtime, the first time it's needed. Thus, the performance hit is essentially zero.

https://godbolt.org/z/dG3GKPv1n

**Comment by UnorderedSigh** [comment]
Last tested and known to work Thu, 23 Nov 2023 00:45:43 UTC.

File: source/Ship.cpp [hunk 3]
```diff
@@ -64,31 +64,30 @@ namespace {
...
 	const double MAXIMUM_TEMPERATURE = 100.;
 
-	// Scanning takes between 2 and 10 seconds (SCAN_TIME / MAX_SCAN_STEPS and SCAN_TIME / MIN_SCAN_STEPS)
+	// Scanning takes up to 10 seconds (SCAN_TIME / MIN_SCAN_STEPS)
 	// dependent on the range from the ship (among other factors).
 	// The scan speed uses a gaussian drop-off with the reported scan radius as the standard deviation.
 	const double SCAN_TIME = 600.;
 	// Always gain at least 1 step of scan progress for every frame spent scanning while in range.
 	// This ensures every scan completes within 600 frames (10 seconds) of being in range.
 	const double MIN_SCAN_STEPS = 1;
```
Comment (Amazinite) [inline source/Ship.cpp:73]:
```suggestion
	const double MIN_SCAN_STEPS = 1.;
```

File: source/Ship.cpp [hunk 4]
```diff
@@ -64,31 +64,30 @@ namespace {
...
-	// Gain no more than 5 steps of scan progress for every frame spent scanning while in range.
-	// This ensures no scan takes fewer than 120 frames (2 seconds.)
-	const double MAX_SCAN_STEPS = 5; // minimum of 2 seconds to scan
+	// Exponential dropoff of scan rate starts at scan rate of SCAN_TIME/LINEAR_RATE
+	// with an exponent of SCAN_DROPOFF_EXPONENT.
+	const double LINEAR_RATE = 5;
+	const double SCAN_DROPOFF_EXPONENT = 5;
```
Comment (Amazinite) [inline source/Ship.cpp:77]:
```suggestion
	const double LINEAR_RATE = 5.;
	const double SCAN_DROPOFF_EXPONENT = 5.;
```

File: source/Ship.cpp [hunk 5]
```diff
@@ -64,31 +64,30 @@ namespace {
...
 
-	// These numbers ensure it takes 10 seconds for a Cargo Scanner to scan
-	// a Bulk Freighter at point blank range. Any ship with less than 40
-	// cargo space takes as long as a ship with 40 cargo space.
+	// In Ship::Scan, ships smaller than this are treated as being this size.
 	const double SCAN_MIN_CARGO_SPACE = 40;
```
Comment (Amazinite) [inline source/Ship.cpp:80]:
```suggestion
	const double SCAN_MIN_CARGO_SPACE = 40.;
```

File: source/Ship.cpp [hunk 6]
```diff
@@ -64,31 +64,30 @@ namespace {
...
-	const double SCAN_CARGO_FACTOR = 3;
-
-	// This ensures it takes 10 seconds for an Outfit Scanner to scan a
-	// Bactrian at point blank range. Any ship with less than 200 outfit
-	// space takes as long as a ship with 200 outfit space.
 	const double SCAN_MIN_OUTFIT_SPACE = 200;
```
Comment (Amazinite) [inline source/Ship.cpp:81]:
```suggestion
	const double SCAN_MIN_OUTFIT_SPACE = 200.;
```

File: source/Ship.cpp [hunk 7]
```diff
@@ -64,31 +64,30 @@ namespace {
...
-	const double SCAN_OUTFIT_FACTOR = 10;
 
-	// Formula for the scan outfit or cargo factor is:
-	// factor = pow(sqrt(scanEfficiency) * framesToFullScan / SCAN_TIME, 1.5) / referenceSize
+	// Formula for calculating scan speed tuning factors:
+	// factor = pow(framesToFullScan / (SCAN_TIME * sqrt(scanEfficiency)), -1.5) / referenceSize
+
+	// Cargo scanner (5) takes 10 seconds (600/600=1.0) to scan a Bulk freighter (600 space) at 0 range
+	const double SCAN_CARGO_FACTOR = pow(1.0 / sqrt(5), -1.5) / 600;
```
Comment (Amazinite) [inline source/Ship.cpp:87]:
```suggestion
	const double SCAN_CARGO_FACTOR = pow(1.0 / sqrt(5.), -1.5) / 600.;
```

File: source/Ship.cpp [hunk 8]
```diff
@@ -64,31 +64,30 @@ namespace {
...
+
+	// Outfit scanner (15) takes 10 seconds (600/600=1.0) to scan a Bactrian (740 space) at 0 range
+	const double SCAN_OUTFIT_FACTOR = pow(1.0 / sqrt(15), -1.5) / 740;
```
Comment (Amazinite) [inline source/Ship.cpp:90]:
```suggestion
	const double SCAN_OUTFIT_FACTOR = pow(1.0 / sqrt(15.), -1.5) / 740.;
```

File: source/Ship.cpp [hunk 9]
```diff
@@ -64,31 +64,30 @@ namespace {
...
-	// space takes as long as a ship with 200 outfit space.
 	const double SCAN_MIN_OUTFIT_SPACE = 200;
-	const double SCAN_OUTFIT_FACTOR = 10;
 
-	// Formula for the scan outfit or cargo factor is:
-	// factor = pow(sqrt(scanEfficiency) * framesToFullScan / SCAN_TIME, 1.5) / referenceSize
+	// Formula for calculating scan speed tuning factors:
+	// factor = pow(framesToFullScan / (SCAN_TIME * sqrt(scanEfficiency)), -1.5) / referenceSize
+
+	// Cargo scanner (5) takes 10 seconds (600/600=1.0) to scan a Bulk freighter (600 space) at 0 range
```
Comment (Amazinite) [inline source/Ship.cpp:86]:
```suggestion
	// Cargo scanner (5) takes 10 seconds (600/600=1.0) to scan a Bulk freighter (600 space) at 0 range.
```

File: source/Ship.cpp [hunk 10]
```diff
@@ -64,31 +64,30 @@ namespace {
...
+	const double SCAN_CARGO_FACTOR = pow(1.0 / sqrt(5), -1.5) / 600;
+
+	// Outfit scanner (15) takes 10 seconds (600/600=1.0) to scan a Bactrian (740 space) at 0 range
```
Comment (Amazinite) [inline source/Ship.cpp:89]:
```suggestion
	// Outfit scanner (15) takes 10 seconds (600/600=1.0) to scan a Bactrian (740 space) at 0 range.
```

**Review by Amazinite — COMMENTED** [review]
Feeling much better.
