### PR TITLE
fix(mechanics): Fix blast damage not affecting minables

### LINKED ISSUE #9785: Shunt-Strike Turret does not damage asteroids
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I captured a Rano'erek equipped with four Shunt-Strike Turrets and a Banisher Grav-Turret. These turrets are mining outfits, so I was confused when I noticed that it was taking me much longer than I expected to break asteroids. I installed a tactical scanner and discovered that, actually, these turrets aren't doing *any* corrosion damage to asteroids. Only the Banisher was doing damage.

### Steps to Reproduce

1. Equip at least one Shunt-Strike Turret on your flagship
2. Fire at an asteroid
3. The asteroid will not begin taking any corrosion damage - the visual effect that would indicate it is taking corrosion damage is missing as well

### Expected Behavior

Each Shunt-Strike Turret should do 200 damage per shot or 400 damage per second in the form of corrosion.

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

openSUSE Tumbleweed snapshot 20240111

### Game Source

Steam

### Game Version

0.10.5

### Additional Information

I'm not sure when this was introduced, but I know I've mined with Shunt-Strike Turrets before without this issue.

### PR DESCRIPTION
**Pull request by TomGoodIdea**
**Bug fix**

This PR fixes #9785.

## Summary
Implemented blast damage for minables.

## Testing Done
yes™.

## Wiki Update
N/A

## Performance Impact
hopefully none.

### CODE REVIEW

**Review by Koranir — APPROVED** [review]

**Review by Hurleveur — APPROVED** [review]
Code looks good, I tested it with a big blast radius weapon and it worked against asteroids directly and indirectly, by targeting a nearby ship for instance

**Comment by TomGoodIdea** [comment]
> Still, I can't so far playtest-prove that "trigger radius" works on 'roids too with this? Would be fine if it didn't, but if so care should be taken that the wiki reflects this.

I haven't touched the trigger radius code, but it should be trivial with this PR's groundwork. I can do it as a follow-up PR.

File: source/Minable.h [hunk 1]
```diff
@@ -89,6 +90,8 @@ class Minable : public Body {
 
 	// Get hull remaining of this asteroid, as a fraction between 0 and 1.
 	double Hull() const;
+	// Get max hull of this asteroid.
```
Comment (tibetiroka) [inline source/Minable.h:93]:
```suggestion
	// Get the maximum hull value of this asteroid.
```

**Review by tibetiroka — COMMENTED** [review]
Looks good. It's more of a feature than a bugfix, so it'll have to wait for the unstable. I'll test it after the stable release is out, and hopefully merge it.

**Review by tibetiroka — APPROVED** [review]
Works. Thanks for making this!
