### PR TITLE
Set the default jump fuel on the outfit, not just internally for navigation

### LINKED ISSUE #10729: Outfits without defined Jump Fuel don't mention the default 100 fuel cost
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you make an outfit that has a jump capacity of any number, but do not give it a jump fuel attribute at all, it defaults to 100, but does not show this in the stats panel. This is a clarity issue, that should probably be resolved in two ways:

1. Make all vanilla outfits capable of jumping have a fuel cost of some number
2. Adjust the stat panel so it displays the default jump cost of 100, if one was not assigned.

The Emerald Sword is a vanilla example of this issue; the Fusion Drive has hyperjump capability, but no fuel cost assigned, thus it defaults to costing 100 fuel to jump, but, fails to mention this to the player. While it is implied as every other jump method requires fuel, stating it explicitly is probably best.

### Steps to Reproduce

1. Acquire the Emerald Sword
2. Go to an outfitter
3. remove the jump drive
4. See the lack of a fuel cost stat on the Fusion Drive
5. launch & jump
6. notice spent fuel

### Expected Behavior

The stat panel should show the default jump fuel cost, if none is assigned.

### Screenshots

image
image
image
image

### Link to save file

-irrelevant-

### Operating System

Windows 10

### Game Source

Steam

### Game Version

v10.10

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by TomGoodIdea**
**Feature**

This PR addresses the bug/feature described in issue #10729 (closes #10729).

## Summary
Currently, the default jump fuel values (200 for jump drives, 150 for scram drives, and 100 for hyperdrives) are defined in ShipJumpNavigation. OutfitDisplay doesn't know about them, so if there's no custom-defined fuel cost, it shows nothing. With my changes, the defaults are set on the outfits, which means they are displayed normally.

Also added two new attributes: "hyperdrive fuel" and "jump drive fuel" that control the fuel consumption. They have priority over "jump fuel". Example:
```
outfit "Combined Drive"
	"jump fuel" 300
	"scram drive" .5
	"hyperdrive fuel" 180
	"jump drive" 1
```
This outfit uses 180 fuel for hyperlane (scram drive) jumps, and 300 fuel for non-lane jumps (no "jump drive fuel", so "jump fuel" is used).

## Testing Done
haven't tested after adding the new attributes, so
none.

## Wiki Update
https://github.com/endless-sky/endless-sky-wiki/pull/76

## Performance Impact
N/A

### CODE REVIEW

File: source/Outfit.cpp [hunk 1]
```diff
@@ -328,10 +332,18 @@ void Outfit::Load(const DataNode &node)
 					+ pluralName + "\".");
 	}
 
+	// Set the default jump fuel if not defined.
+	bool isHyperdrive = attributes.Get("hyperdrive"),
+		isScramDrive = attributes.Get("scram drive"),
+		isJumpDrive = attributes.Get("jump drive");
```
Comment (tibetiroka) [inline source/Outfit.cpp:338]:
```suggestion
	bool isHyperdrive = attributes.Get("hyperdrive");
	bool isScramDrive = attributes.Get("scram drive");
	bool isJumpDrive = attributes.Get("jump drive");
```
Might as well do this, as they are already in separate lines.

File: source/ShipJumpNavigation.cpp [hunk 2]
```diff
@@ -225,7 +218,7 @@ void ShipJumpNavigation::ParseOutfit(const Outfit &outfit)
 		double distance = outfit.Get("jump range");
 		if(distance <= 0.)
 			distance = System::DEFAULT_NEIGHBOR_DISTANCE;
-		double cost = CalculateFuelCost(DEFAULT_JUMP_DRIVE_COST);
+		double cost = CalculateFuelCost();
 
 		UpdateJumpDriveCosts(distance, cost);
 	}
```
Comment (tibetiroka) [inline source/ShipJumpNavigation.cpp:224]: This is going to behave differently if an outfit is both an HD and JD. Previously, it would have different costs for the two jumps, but now they both use the JD's default cost.

Comment (tibetiroka) [reply source/ShipJumpNavigation.cpp:224]: I think that's fine. "hyperdrive fuel" and "jump drive fuel" both defaulting to the "jump fuel" value. I don't think we need a separate value for the scram drive.

**Review by tibetiroka — APPROVED** [review]
