### PR TITLE
Fix usage of SDL_GetPrefPath

### LINKED ISSUE #9295: SDL_GetPrefPath being used incorrectly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently, `Files::Init()` calls `SDL_GetPrefPath()` this way:
```cpp
		char *str = SDL_GetPrefPath("endless-sky", "saves");
		...
		savePath = str;
		config = savePath.substr(0, savePath.rfind('/', savePath.length() - 2) + 1);
```

The two arguments to `SDL_GetPrefPath()` are `org` and `app`. `org` is allowed to be null, but `app` is not. This means that the `app` argument is `"saves"`, as if the name of the application is "saves". 

The other thing that looks wrong is that we are taking the path given to us by `SDL_GetPrefPath()`, which presumably is the only safe place for us to write files, and we are going to the *parent* directory get the `config` variable, which we then use to determine where all the other paths come from. This is not a safe operation. 

### Steps to Reproduce

Run the program. 

### Expected Behavior

I think the expected usage should look more like this:
```cpp
		char *str = SDL_GetPrefPath(nullptr, "endless-sky");
		...
		config = str;
		savePath = config + "saves/";

```

If I read the OS-specific SDL_GetPrefPath() implementations correctly, this will produce an identical preferences file structure to the one already currently used. 

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

linux and android

### Game Source

Built from source

### Game Version

0.10.2

### Additional Information

I think the mobile port is the only usecase that seems to be adversely affected by this bug. Regardless of the arguments to `SDL_GetPrefPath()`, the android version of SDL_sysfilesystem.c always returns the `java.io.File::getFilesDir()` directory. When we take the *parent* of that directory, we end up in a folder that is used by android subsystem for its own purposes. This means that the file structure used by the android preferences path is wrong, and so far has only avoided corrupting its own state through sheer luck. This is not necessarily going to work in future versions of android or SDL though.

### PR DESCRIPTION
**Pull request by quyykk**
**Bugfix:** This PR addresses fixes #9295 

## Fix Details

This corrects the SDL_GetPrefPath call, to properly get the user-defined config folder on every platform. This was broken on Android.

/cc @thewierdnut 

## Testing Done

Tested this on Linux. I haven't tested the others, but I don't expect there to be any problems.

### CODE REVIEW

File: source/Files.cpp [hunk 1]
```diff
@@ -561,6 +549,21 @@ void Files::Write(FILE *file, const string &data)
 
 
 
+void Files::CreateDirectory(const std::string &path)
```
Comment (thewierdnut) [inline source/Files.cpp:552]: windows `#defines CreateDirectory` to its own garbage. you will want a different name here.

Comment (quyykk) [reply source/Files.cpp]: oh right I forgot about that, thanks

Comment (thewierdnut) [reply source/Files.cpp]: If you want to use MakeDir, then I won't have to rewrite this: https://github.com/thewierdnut/endless-mobile/blob/android/source/Files.cpp#L689

Comment (quyykk) [reply source/Files.cpp]: Does that function create any directory that doesn't exist in the given path? Why/where do you need this?

Comment (thewierdnut) [reply source/Files.cpp]: I'm not saying steal that whole function, just proposing an alternative name.

Comment (thewierdnut) [reply source/Files.cpp]: And yeah... the implementation I wrote recursively creates all the directories (think `mkdir -p`) in the given path. That was needed for zip processing though, which you guys don't have.

Comment (quyykk) [reply source/Files.cpp]: oh I see, idk I find CreateFolder clearer

Comment (thewierdnut) [reply source/Files.cpp]: Meh. I moved all the zip processing into the java code. I can probably delete my code.

Comment (quyykk) [reply source/Files.cpp]: on an unrelated note, did you see this https://github.com/libsdl-org/SDL/issues/8129

Comment (thewierdnut) [reply source/Files.cpp]: Now that std::filesystem is a thing, it seems pointless. I wish we had this 10 years ago.

Comment (quyykk) [reply source/Files.cpp]: Can std::filesystem be used on Android? if so that's dope

Comment (thewierdnut) [reply source/Files.cpp]: hm... It looks like it is there, though I haven't tried it yet:
```
android-ndk-r20b$ find . -iname filesystem
./toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/filesystem
./toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/experimental/filesystem
./sources/cxx-stl/llvm-libc++/include/filesystem
./sources/cxx-stl/llvm-libc++/include/experimental/filesystem
./sources/cxx-stl/llvm-libc++/test/std/experimental/filesystem
./sources/cxx-stl/llvm-libc++/test/libcxx/experimental/filesystem
```

**Review by thewierdnut — APPROVED** [review]
Code looks good to me.

I've compiled and tried it out with an existing install, and a new install on a linux computer, and it behaves as expected.

File: source/Files.cpp [hunk 2]
```diff
@@ -561,6 +554,21 @@ void Files::Write(FILE *file, const string &data)
 
 
 
+void Files::CreateFolder(const std::string &path)
+{
+	if(Files::Exists(path))
```
Comment (warp-core) [inline source/Files.cpp:559]: `Files::Init` doesn't seem to include the `Files::` prefix on other methods in `Files` that it calls, like `Exists` and `CreateFolder`. Any reason why this method is different? Should it always include the prefix?
