### PR TITLE
bugfix: MOVE_TO orders refer to a specific System

### LINKED ISSUE #2382: Escorts move to selected position regardless of system
If I right click somewhere (telling the escorts to go there), and then jump out of the system, the escorts jump as well, and then move to the same corresponding spot in the next system. The command should disengage when we move to another system, or make the escorts hold in the current system (so they do not jump), because it isn't useful to have everyone park in the corresponding spot in the next system.

### LINKED ISSUE #2580: Issuing MoveTo order prevents (selected) out-of-system escorts from following the Player
**To Reproduce:** Move to a new system and issue a MOVE_TO order.

**Expected behavior:** (selected) escorts follow the player and upon entering the player's system, follow the MOVE_TO order.

**Observed behavior:** If the (selected) escorts are in the player's system, they execute the MOVE_TO order. If the (selected) escorts are not in the player's system, they stop following the player and remain in their current system(s).

fb175d6917fc1aaf010bfaef46b0ebd6218edb56 was added with the goal of preventing escorts in the progress of executing / having already executed a MOVE_TO from following the player. It just also happens to make a _new_ MOVE_TO order have priority over the _existing_ FOLLOW behavior.

### PR DESCRIPTION
**Pull request by tehhowch**
Issuing MOVE_TO orders now includes a target system, allowing selected escorts to navigate across system boundaries to the specified position, instead of navigating to that point in their current system.

Ref #2584, Closes #2580, Closes #2382

### CODE REVIEW

File: source/AI.cpp [hunk 1]
```diff
@@ -824,11 +825,19 @@ bool AI::FollowOrders(Ship &ship, Command &command) const
...
+		DistanceMap distance(ship, it->second.targetSystem);
+		const System *to = distance.Route(ship.GetSystem());
+		ship.SetTargetSystem(to);
+		return false;
+	}
 	else if(type == Orders::HOLD_POSITION || type == Orders::MOVE_TO)
 	{
-		if(ship.Velocity().Length() > .001 || !ship.GetTargetShip())
+		if(it->second.point && ship.Position().Distance(it->second.point) > 20.)
+			MoveTo(ship, command, it->second.point, Point(), 10., .1);
```
Comment (endless-sky) [inline source/AI.cpp]: Rather than moving these these two lines into this if clause, it would be clearer to just turn the original "if" in line 827 into an "else if."

That would limit the code changes to what's strictly necessary (just adding yout one new "if" clause for moving to a different system). Also, checking `type == Orders::MOVE_TO` is clearer than checking `it->second.point`.
