### PR TITLE
Fix #4364

### LINKED ISSUE #4364: Outfitter autorefill installs too much ammo
**Describe the bug**
It's possible for a ship with 5 EMP Torpedo Bay launchers to receive 565 EMP Torpedo missiles.

**To Reproduce**
1. Load the attached savefile 
2. Enter the outfitter
3. Sell all EMP Torpedo missiles from **all** ships
4. Exit outfitter
5. Enter outfitter
6. Click OK in the "Do you want to refill ammo for all ships" dialog
7. See screenshot

**Expected behavior**
Don't install more missiles than the ship has capacity for

**Screenshots**
2019-06-14-194337_175x472_scrot

**System (please complete the following information):**
 - Version: 0.9.9 and current git

**Link to save file**
[Leto_AtreidesMISSILEDUPLICATE.txt](https://github.com/endless-sky/endless-sky/files/3291995/Leto_AtreidesMISSILEDUPLICATE.txt) by Blop on discord

### PR DESCRIPTION
**Pull request by jostephd**
See #4364 and the commit messages for details

### CODE REVIEW

File: source/Outfit.cpp [hunk 1]
```diff
@@ -202,6 +202,7 @@ int Outfit::CanAdd(const Outfit &other, int count) const
 			count = value / -at.second + EPS;
 	}
 	
+	// TODO: return max<int>(0, count);
```
Comment (tehhowch) [inline source/Outfit.cpp]: ?

File: data/tooltips.txt [hunk 2]
```diff
@@ -496,3 +496,6 @@ tip "no fuel?"
 
 tip "insufficient energy to fire?"
 	`This ship has insufficient energy storage to fire an installed weapon.`
+
+tip "negative attribute!"
```
Comment (tehhowch) [inline data/tooltips.txt]: Negative attributes are not necessarily a bug.

Comment (Amazinite) [inline data/tooltips.txt]: Unrelated change. But as stated, this isn't even necessarily something that needs changed. Ref: https://github.com/endless-sky/endless-sky/issues/1402#issuecomment-239461582

File: source/Outfit.cpp (hunk 1 above)
Comment (jostephd) [reply source/Outfit.cpp]: If a ship has 5 EMP Torpedo Bay launchers and 500 EMP Torpedo missiles installed and _then_ you enter the outfitter, CanAdd will return `-455`. I thought it should return `0` in that case so I left a comment to remember to get back and review that question later.

File: data/tooltips.txt (hunk 2 above)
Comment (jostephd) [reply data/tooltips.txt]: I thought it would be a bug because of the error message when trying to install such an outfit:

https://github.com/endless-sky/endless-sky/blob/de6b31469601aa8ef5d1ad356ebbd65416bbe1aa/source/OutfitterPanel.cpp#L472-L474

Comment (jostephd) [reply data/tooltips.txt]: > Unrelated change

It is related in that the sanity check would have prevented Blop from launching with more ammo than he has capacity for. I agree that it's a separate change and that's why I put it in a separate commit (which I have now removed). Thanks for the reference.

File: source/OutfitterPanel.cpp [hunk 3]
```diff
@@ -832,6 +832,7 @@ void OutfitterPanel::Refill()
 				neededAmmo -= fromCargo;
 				// Then, buy at reduced (or full) price.
 				int available = outfitter.Has(outfit) ? neededAmmo : max<int>(0, player.Stock(outfit));
+				available = min<int>(neededAmmo, available);
```
[the remark this answers is not in the document]
Comment (jostephd) [reply source/OutfitterPanel.cpp]: Done
