### PR TITLE
Fix(code): Prevent manual hyperjumping from locking in a planned route, which enables the player to manually change destinations.

### LINKED ISSUE #7817: bug(code): Manual selecting of a hyperjump in flight locks in a nav route that has to be cleared in the map.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I select a hyperjump by aligning my ship along one of the hyperlanes leaving the system (using the arrows around the minimap), sometimes there are two options close together and I accidentally pick one instead of the other. Realizing this, I break the autopilot sequence, correct my alignment to the other hyperland, and restart the jump. However, this doesn't work, as the initial starting of the hyperjump appears to lock-in or set a hyperjump route to the next system, so nothing short of opening the map and removing that hyperroute will enable me to jump anywhere else but to the initial erroneously selected system.

### Steps to Reproduce

1. Be flying in space.
2. Make sure you have no hyperlanes selected and no route planned in the map.
3. Align your ship with a hyperlane.
4. Hit "jump"
5. Use a movement key to cancel the hyperjump sequence.
6. Align yourself with a different hyperlane.
7. Hit jump.
8. See how you return to jumping out the initially selected hyperlane.

### Expected Behavior

When free-jumping or manually navigating around the galaxy, I expect that canceling a jump and reorienting towards a different hyperlane would result in my new jump using the new orientation, not returning to the old canceled hyperjump.

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

Windows 10 Pro

### Game Source

Built from source

### Game Version

0.9.17 alpha, up to date with continuous as of Dec 09

### Additional Information

Immediately preferred solution:
1. Manually targeted hyperjumps always hyperjump along the route the ship is aimed at. In other words, manually targeting a hyperjump never locks in a route.

Alternative solution:
2. Provide a shortcut key for clearing the current route, setable in the preferences.
3. Provide a setting to determine whether or not a manually targeted hyperjump locks in a route, or always uses where the ship is pointing.

### PR DESCRIPTION
**Pull request by Zitchas**
**Bugfix:** This PR addresses fixes #7817 

I would like to note that it appears that this might actually be intentional behavior. So while I consider this a fix, it also seems that someone, somewhere, wanted it to work this way.

## Fix Details
Thanks to @vitalchip for working out how to do this and providing detailed instruction. I only implemented their work in up-to-date ES.

This removes the code that pushes a manually selected hyperjump up to the route. The reason for wanting to remove this is that it is fairly easy to make a mistake, and one should be able to simply break the hyperjump sequence, re-orient, and continue on ones way. The fact that the initial manual jump didn't merely select the destination, it actually locks it in as a planned route on the map, means that it is impossible to change one's mind or correct a mistake without actually opening the map and clearing the route.

Checking the git blame, this appears to have been put in place by @tehhowch for "thread safety", although that is unclear exactly how or what that means. It also specifies that this is used to enable the player to just the jump key to rotate between potential destinations while in the map. This makes it sound like something put in place to enabled more keyboard centric gameplay from the map may have interfered with the ability to do something similar with our in-flight mechanics. Which is kind of ironic.

So, for my part, I'll be testing to see if this broke the map pane functionality. If it did, how can we retain that functionality whithout blocking the in-flight hyperjump correction that I'm trying to enable?

## Testing Done
Flew it around.

That being said, given that this was done intentionally, I would very much like additional eyes on it to determine if there's any untoward effects.

## Save File
None required. Literally any pilot, anywhere, can test this, as it is basic hyperjumping and navigation.

### CODE REVIEW

**Comment by Hurleveur** [comment]
I don't know much about thread safety but I think that part could be important.
What we could have instead of this is a new key press to reset any travel plan the player may have (or just remove the last element of it) and then it would naturally choose again the system that corresponds to the direction you're going. Maybe alt J or smth idk.
Even if the tests run maybe it's smth that would bother us for the future. An alternative would be that clicking J twice in quick succession would change the target system to the next one we can reach.

If someone that knows more about threads confirms its fine then I'm fine with this at well though.

**Comment by Zitchas** [comment]
Reviewing Tehhowch's comment on the commit that git blame has attached to one of these lines, I have learned something new:

Not only can we use the hyperjump key on the map pane to selected a destination and rotate between options, if we then hold shift while tapping the hyperjump key, it will move on to the end of the selected hyperjump and start plotting the next one, which can then be rotated through. So one can actually make full hyperroutes using just the hyperjump key, shift, and delete (delete erases backwards along the route, one step at a time). As best I can tell, no functionality here has been impacted, at least at the user-facing level. (I'm curious as to how many people even knew this was a thing)

**Comment by Hurleveur** [comment]
Well that's from the map panel yeah so I don't think you even need to test it it's unrelated to this change (except mb if you start by planning the jump from in space and then continue in the map, idk what would happen then but we prob set securities up for that?)
I didn't know just always been using my mouse but could be useful for gamepad etc controls

File: source/Engine.cpp [hunk 1]
```diff
@@ -555,8 +555,8 @@ void Engine::Step(bool isActive)
 
 	const System *currentSystem = player.GetSystem();
 	// Update this here, for thread safety.
-	if(!player.HasTravelPlan() && flagship && flagship->GetTargetSystem())
-		player.TravelPlan().push_back(flagship->GetTargetSystem());
+	// if(!player.HasTravelPlan() && flagship && flagship->GetTargetSystem())
+	//	 player.TravelPlan().push_back(flagship->GetTargetSystem());
```
Comment (RisingLeaf) [inline source/Engine.cpp:559]: Delete it or leave it or add a comment why it is commented out, but do not leave it just like this

**Review by RisingLeaf — CHANGES_REQUESTED** [review]

File: source/Engine.cpp (hunk 1 above)
Comment (Zitchas) [reply source/Engine.cpp:559]: Yep, that makes sense. I'll delete it, now that I know it works.

**Comment by Hurleveur** [comment]
This way still feels like a hack to me, we shouldnt be touching that code I think we should instead just set a bool for whether or not the player has set the destination from the map or not (which would be set to true when we create a travelplan from the map but not when this if here creates a travelplan)

**Comment by Zitchas** [comment]
I'm open to alternatives, however my coding level is at "take other people's provided code and integrate it" level, not "create new stuff that spans multiple areas."

File: source/AI.cpp [hunk 2]
```diff
@@ -3655,7 +3655,7 @@ void AI::MovePlayer(Ship &ship, const PlayerInfo &player, Command &activeCommand
 	}
 	else if(activeCommands.Has(Command::JUMP | Command::FLEET_JUMP))
 	{
-		if(!ship.GetTargetSystem() && !isWormhole)
+		if((!ship.GetTargetSystem() || player.TravelPlan().empty()) && !isWormhole)
```
Comment (RisingLeaf) [inline source/AI.cpp:3658]: this line could need a comment now that it is more complex

**Review by RisingLeaf — CHANGES_REQUESTED** [review]

File: source/Engine.cpp (hunk 1 above)
Comment (RisingLeaf) [reply source/Engine.cpp:559]: I am still not sure if this is safe, thread safety is a very important thing

Comment (RisingLeaf) [reply source/Engine.cpp:559]: oh, wait, no it should be fine, what he means is do it here instead of somewhere else, sorry I am stupid

File: source/AI.cpp (hunk 2 above)
Comment (vitalchip) [reply source/AI.cpp:3658]: You could chop it down to if(player.TravelPlan().empty() && !isWormhole). GetTargetSystem is no longer required

File: source/Engine.cpp (hunk 1 above)
Comment (Hurleveur) [reply source/Engine.cpp:559]: Oh so this is fine? Got me confused as well so idk

File: source/AI.cpp (hunk 2 above)
Comment (Zitchas) [reply source/AI.cpp:3658]: Line has been trimmed as described. Thanks for the suggestion!

**Comment by Zitchas** [comment]
The comments have been removed and the line trimmed as per the suggestions. Will be pushed momentarily.

**Review by quyykk — APPROVED** [review]
Looks good!
