### PR TITLE
fix(npe): Fix a crash in Engine::Place when you have no flagship

### LINKED ISSUE #12297: Crash when landing on quarg planet with quarg outfits.
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

If you land on a quarg planet with quarg outfits and hit the imprisonment condition, the game crashes on master. 

### Steps to Reproduce

1. Buy quarg ship (I used all-start plugin)
2. Land on quarg planet or ringworld

### Expected Behavior

The imprisonment ending

### Screenshots

_No response_

### Save File

[qu arg.txt](https://github.com/user-attachments/files/25472549/qu.arg.txt)

just load the `qu arg` save and jump to enif on the right and attempt to land on lagrange

### Error Log

In `Engine::Place()` the `player.FlagshipPtr()` call on line 329 is returning null. Later it attempts to dereference it on line 401. 

```
#0  0x000055555bbb5a1f in Point::operator- (this=0x7ffff210b560, point=...) at /home/rian/git/endless-sky/source/Point.cpp:119
#1  0x000055555bbb5d2e in Point::operator- (this=0xb0) at /home/rian/git/endless-sky/source/Point.cpp:142
#2  0x000055555ac95f35 in Body::Center (this=0x10) at /home/rian/git/endless-sky/source/Body.cpp:88
#3  0x000055555af240bc in Engine::Place (this=0x5210004fc580) at /home/rian/git/endless-sky/source/Engine.cpp:404
#4  0x000055555b4a4674 in MainPanel::OnCallback (this=0x5210004fc500) at /home/rian/git/endless-sky/source/MainPanel.cpp:169
#5  0x000055555b4c9934 in std::__invoke_impl<void, void (MainPanel::*&)(), MainPanel*&> (__f=@0x503000022120: (void (MainPanel::*)(MainPanel * const)) 0x55555b4a45e0 <MainPanel::OnCallback()>, __t=@0x503000022130: 0x5210004fc500) at /usr/include/c++/14/bits/invoke.h:74
#6  0x000055555b4c9095 in std::__invoke<void (MainPanel::*&)(), MainPanel*&> (__fn=@0x503000022120: (void (MainPanel::*)(MainPanel * const)) 0x55555b4a45e0 <MainPanel::OnCallback()>) at /usr/include/c++/14/bits/invoke.h:96
#7  0x000055555b4c8ae9 in std::_Bind<void (MainPanel::*(MainPanel*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x503000022120, __args=...) at /usr/include/c++/14/functional:513
#8  0x000055555b4c72ce in std::_Bind<void (MainPanel::*(MainPanel*))()>::operator()<, void>() (this=0x503000022120) at /usr/include/c++/14/functional:598
#9  0x000055555b4c3b47 in std::__invoke_impl<void, std::_Bind<void (MainPanel::*(MainPanel*))()>&>(std::__invoke_other, std::_Bind<void (MainPanel::*(MainPanel*))()>&) (__f=...) at /usr/include/c++/14/bits/invoke.h:61
#10 0x000055555b4c0336 in std::__invoke_r<void, std::_Bind<void (MainPanel::*(MainPanel*))()>&>(std::_Bind<void (MainPanel::*(MainPanel*))()>&) (__fn=...) at /usr/include/c++/14/bits/invoke.h:111
#11 0x000055555b4bdaca in std::_Function_handler<void (), std::_Bind<void (MainPanel::*(MainPanel*))()> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/14/bits/std_function.h:290
#12 0x000055555aea9301 in std::function<void()>::operator() (this=0x5150000df800) at /usr/include/c++/14/bits/std_function.h:591
#13 0x000055555b951142 in PlanetPanel::Step (this=0x5150000df780) at /home/rian/git/endless-sky/source/PlanetPanel.cpp:100
#14 0x000055555c00a8f0 in UI::StepAll (this=0x7ffff282ee70) at /home/rian/git/endless-sky/source/UI.cpp:101
#15 0x000055555a92f470 in GameLoop (player=..., queue=..., conversation=..., testToRunName="", debugMode=false) at /home/rian/git/endless-sky/source/main.cpp:431
#16 0x000055555a92b28a in main (argc=3, argv=0x7fffffffdb58) at /home/rian/git/endless-sky/source/main.cpp:255
```

### Operating System

Debian trixie

### Game Source

Built from source

### Game Version

master (3d21f7a785b6700400decfc1784daaec3a787c4c)

### Additional Information

I placed a pointer check around the `camera.SnapTo(flagship->Center())` line on the mobile port at Engine.cpp:401, and it seems to complete the imprisonment dialog ok. I don't know why the flagship was modified to allow it to be null though, so there may be other consequences I am unaware of.

### PR DESCRIPTION
**Pull request by Amazinite**
**Bug fix**

Closes #12297.

## Acknowledgement

- [x] I acknowledge that I have read and understand the [Contributing](https://github.com/endless-sky/endless-sky/blob/master/docs/CONTRIBUTING.md) article.

## Summary

Change Engine::Place to do the same thing as Engine::Step and use the player's current stellar object to position the camera if there is no flagship, and just stop all camera movement if there is no stellar object either.

## Testing Done

No, but I'm pretty sure.

### CODE REVIEW

File: source/Engine.cpp [hunk 1]
```diff
@@ -401,7 +401,12 @@ void Engine::Place()
 	// that all special ships have been repositioned.
 	ships.splice(ships.end(), newShips);
 
-	camera.SnapTo(flagship->Center());
+	if(flagship)
+		camera.SnapTo(flagship->Center());
+	else if(player.GetStellarObject())
+		camera.SnapTo(player.GetStellarObject()->Position());
+	else
+		camera.SnapTo(camera.Center());
```
Comment (warp-core) [inline source/Engine.cpp:409]: Does this have any effect?

File: source/Engine.cpp [hunk 2]
```diff
@@ -401,7 +401,12 @@ void Engine::Place()
 	// that all special ships have been repositioned.
 	ships.splice(ships.end(), newShips);
 
-	camera.SnapTo(flagship->Center());
+	if(flagship)
+		camera.SnapTo(flagship->Center());
+	else if(player.GetStellarObject())
+		camera.SnapTo(player.GetStellarObject()->Position());
```
Comment (warp-core) [inline source/Engine.cpp]: We already retrieved this value. It's in `planetPos`.

Comment (Amazinite) [inline source/Engine.cpp]:
```suggestion
	else if(object)
		camera.SnapTo(planetPos);
```

File: source/Engine.cpp (hunk 1 above)
Comment (Amazinite) [reply source/Engine.cpp:409]: It kills camera movement if there was any.
