### PR TITLE
fix(mechanics): Fix weapon jamming accumulation

### LINKED ISSUE #10442: (Bug) Weapons Still Not Firing After Scramble Wears Off
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As a foreword, I have found **very** few consistencies with iterations of this bug. Please forgive the ensuing onslaught of "likelies" and similar adjectives.

Scrambling Damage is designed to stop weapons from firing, but this is very particular. After scrambling, a weapon will uncommonly become seemingly permanently disabled; it won't fire for an extended period of time. In some cases, I've had the bug persist for upwards of 10 minutes' time, before just fixing itself and not being able to be retriggered until the next time I jump or take off.

The behaviour is inconsistent with scrambling in the way that it affects weapons. It ignores fire rate (though the bug does seem to like slower firing weapons more), and consistently affects the same weapon, at least for a while, until (presumably) enough changes about the ship's kit for the bug to go to someweapon else.

### Steps to Reproduce

It's hard to give a definitive guide on how to trigger this bug, but I'll do my best.

For best results (based on the corroboration of others), use a Dragonflame Cannon. This bug seems to like it the most (though presumably other slow firing weapons like a Nullifier or whathaveyou would work as well; I've personally had it happen on pulsed beams before).

The second part is simple... If you can get it to happen at all. Fight something with scrambling damage, let it rough you up, then run away and wait for the scramble to dissipate. If the bug has triggered, you won't be able to fire one of your weapons.

### Expected Behavior

I'd assume when scramble is gone I'd be able to fire all my weapons like normal.

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

Windows 11

### Game Source

ESLauncher2

### Game Version

v0.10.9-alpha

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by TomGoodIdea**
**Bug fix**

This PR fixes #10442.

## Summary
Jamming is supposed to reset the reload counter, so that after the (unsuccessful) attempt to fire, you need to wait another reload cycle. But currently there's a bug that causes the cycles to build up, which means that if you try to fire while your ship is scrambled, you may end up with a single "reload" lasting many normal reload cycles.
Edit: this may be even more complicated (see the comments below).

With this patch, a single jam never blocks the weapon for more than one reload cycle.

## Testing Done
It's kinda hard to reliably test this, but it seems to work now.

## Wiki Update
N/A

## Performance Impact
N/A

### CODE REVIEW

**Comment by Amazinite** [comment]
> if you try to fire while your ship is scrambled

How is the Jam function being run in this case? Jam should only run if IsReady is true. IsReady shouldn't be true if the weapon isn't ready to fire, and a jammed weapon means it isn't ready to fire. So how would the Jam function run multiple times before the weapon is ready to fire to cause the reload counter to stack?

**Comment by TomGoodIdea** [comment]
~~that's a good question. it works, but now I don't know why~~

Okay, I found out: if your ship has any anti-missile and there are projectiles nearby, the engine calls `Ship::FireAntiMissile`, which iterates over all hardpoints (doesn't matter if they have anti-missile or not) and calls `Armament::FireAntiMissile` until the missile is destroyed. I managed to get >10 jams/sec on a single turned off Dragonflame just by flying around Wah Ki (to get both scrambling and missiles) with anti-missile systems installed.

But it still doesn't explain how it passes the IsReady check.
https://github.com/endless-sky/endless-sky/blob/eb8ed7e6588ce6871ff7bee84d8fed7bd7d2c75b/source/Hardpoint.cpp#L181-L185
It doesn't use `reload`, only `burstReload`. I think it still should return false if a non-burst weapon needs to reload, but my testing says otherwise.

**Comment by tibetiroka** [comment]
So uh... should this be a draft, considering that you can't get it to work the way it's supposed to?

**Comment by TomGoodIdea** [comment]
ok, but if by "the way it's supposed to work" you mean fixing IsReady, I'm not really sure how to do that

**Comment by TomGoodIdea** [comment]
alright, I think I finally found the source of the problem, but solving it may require a refactor of the whole weapon reload code. I'll let you know when it's ready and I'll try to do it before the stable release

**Comment by TomGoodIdea** [comment]
So, the code could perhaps use some more comments, but it's not as bad as I expected.
The problem was that `Jam` wasn't doing everything it should to reset the reload (you can compare it with `Fire` to see the difference).
It was only increasing `reload` and `burstReload` (most weapons have `burstReload` set to 1, so it was being reset every frame), and the check doesn't account for `reload`, allowing the buildup of `reload` (but not `burstReload`). After getting the accumulated scramble, my every weapon was able to fire once (because `burstReload` was 0 and `burstCount` was 1), decreasing `burstCount` to 0, which makes the check fail, and blocking the weapon until `burstCount` was reset to 1, but that can only happen when `reload` reaches 0.

File: source/Hardpoint.cpp [hunk 1]
```diff
@@ -325,6 +325,7 @@ void Hardpoint::Jam()
 	// Reset the reload count.
 	reload += outfit->Reload();
 	burstReload += outfit->BurstReload();
+	--burstCount;
```
Comment (petervdmeer) [inline source/Hardpoint.cpp:328]:
```suggestion
	reload = outfit->Reload();
	burstReload = outfit->BurstReload();
	burstCount = 0;
```
On jamming I would expect the weapon to start as if it wasn't loaded. So setting reload and burstReload to the maximum values they have (and not beyond that due to addition), and the burstCount to zero (since the weapon needs a full reload, there are no bursts present).

I didn't test this, but I don't see how just reducing the burstCount would be semantically correct. (And I also feel we should never have longer reload times than outfit=>Reload()).

Comment (petervdmeer) [reply source/Hardpoint.cpp:328]: Ok, but if the jam-code does exactly the same as the fire code, then the weapon doesn't really get jammed, but it just fires a dud.

I can imagine that that is the behavior that we want, and in that case it's fine for me to just merge this PR as-is.

Comment (petervdmeer) [reply source/Hardpoint.cpp:328]: One small difference I noticed is that the fire code sets `isFiring` to true. I'm not sure what effect that has and if it would also be required.

Comment (TomGoodIdea) [reply source/Hardpoint.cpp:328]: it's not needed to change isFiring here
