### PR TITLE
fix(mechanics): Properly place die effects spawned by projectiles

### LINKED ISSUE #5479: Bug: A die effect jumps back when it's borne by a projectile
**Describe the bug**
A die effect jumps back when it's borne by a projectile, that is, a projectile causes a die effect before the location where it dies.
Please see a video in the Screenshot section.

**To Reproduce**
1. Install [this plugin](https://github.com/endless-sky/endless-sky/files/5464783/test-die-effect-plugin.zip) and use [this savefile](https://github.com/endless-sky/endless-sky/files/5464781/die_effect_savefile.zip) "pom pom.txt".
2. Start "endless-sky" with "-d" option.
3. Load the pilot "pom pom".
4. Depart.
5. Press CapsLock and slow the game speed down.
6. Fire the gun.

**Expected behavior**
A projectile and the die effect should move continuously.

**Screenshot**
Peek 2020-10-30 20-39
A red circle is a projectile, a white is a die effect.

**System (please complete the following information):**
 - OS: Debian GNU/Linux Testing
 - Game Source: Github
 - Version:  current master 70eb5967f20dfd7cc4aaa697cc62d46575e24173

**Link to save file**
[die_effect_savefile.zip](https://github.com/endless-sky/endless-sky/files/5464781/die_effect_savefile.zip)
[test-die-effect-plugin.zip](https://github.com/endless-sky/endless-sky/files/5464783/test-die-effect-plugin.zip)

```
outfit "Pom Pom Gun"
	category "Guns"
	cost 100
	"mass" 5
	"outfit space" -5
	"weapon capacity" -5
	"gun ports" -1
	weapon
		sprite "projectile/red_circle"
		sound "blaster"
		"hit effect" "blaster impact"
		"die effect" "pom pom dead"
		"velocity" 60
		"lifetime" 5
		"reload" 5
		"firing energy" 1
		"firing heat" 1
		"shield damage" 1
		"hull damage" 1

effect "pom pom dead"
	sprite "projectile/white_circle"
	"lifetime" 60
```

### PR DESCRIPTION
**Pull request by Amazinite**
**Bug fix**

This PR addresses the bug described in issue #5479.
Closes #5479.

## Acknowledgement

- [x] I acknowledge that I have read and understand the [Contributing](https://github.com/endless-sky/endless-sky/blob/master/docs/CONTRIBUTING.md) article.

## Summary

When die effects are placed, they currently don't account for the velocity of the parent projectile, hence the behavior seen in the linked issue. This PR changes die effects to have 1.5x the velocity of the parent projectile added to the effect's spawn position. This causes the die effect to appear where the projectile would be next frame had it still been alive.

I'll note that I first tried using an offset of 0.5x, and that did cause the die effect to appear on top of where the projectile was the frame that it died, but that only occurred while my flagship was stationary. As soon as I started moving my flagship, the die effect's origin started to move away from where the projectile was on its last frame. By using an offset of 1.5x, the influence of the flagship's movement goes away... somehow. I'm not entirely sure why that is, tbh. But depending on the style of the die effect, this may or may not be the desirable behavior. I did test how some of the die effects in the game look with and without this behavior, and the velocities that projectiles move at actually meant that the change isn't super big, but the updated behavior does appear better to me, or it at least isn't worse than it was before.

One oddity with this is that die effects don't look very good when used with lasers (they appear half the laser's length ahead of it), but they don't look very good with lasers right now anyway (they appear at the hardpoint). Using an offset of 1x the velocity produced the best result with lasers, but made other weapons I tested not appear as good. Data-defined effect offset time?

## Testing Done + Save File

1. Install [this plugin](https://github.com/user-attachments/files/20684752/test-die-effect.zip) and save file linked in the issue (or just start a new save file, since it's on New Boston).
2. Fire the pom pom gun.
3. Observe that the die effect is placed properly ahead of the projectile instead of jumping back.

### CODE REVIEW

**Comment by Amazinite** [comment]
The plugin I linked in the PR description has a second weapon that the plugin from the issue didn't have. This version of the pom pom gun uses a submunition instead of a die effect. If you fly around with it and fire, you can see that the submunition's position isn't quite right. I think that submunitions might need the same 1.5x velocity offset that the die effects need. Right now they use a 1x velocity offset. Although then laser submunitions couldn't be a thing, since it would appear at the wrong spot. It's not like it's noticeable in practice, so maybe we just leave this as-is.🤔
https://github.com/endless-sky/endless-sky/blob/dfd1687736f854c2cda8188684d007a60de72dd5/source/Projectile.cpp#L83-L87

File: source/Projectile.cpp [hunk 1]
```diff
@@ -144,6 +148,9 @@ void Projectile::Move(vector<Visual> &visuals, vector<Projectile> &projectiles)
 		MarkForRemoval();
 		return;
 	}
+	// Spawn live effects. By using the current position of the projectile and not
+	// adding any offset from the projectile's velocity, effects will appear to spawn
+	// from the back of the projectile.
```
Comment (Amazinite) [inline source/Projectile.cpp]:
```suggestion
	// Spawn live effects. By using the current position of the projectile and not
	// adding any offset from the projectile's velocity, effects will appear to spawn
	// from behind the projectile, as by the time the effect is visible, the projectile
	// will have moved one frame forward from this position.
```

File: source/Projectile.cpp [hunk 2]
```diff
@@ -127,9 +127,13 @@ void Projectile::Move(vector<Visual> &visuals, vector<Projectile> &projectiles)
 		if(lifetime > -1000)
 		{
 			// This projectile didn't die in a collision. Create any death effects.
+			// Place effects ahead of the projectile by 1.5x velocity. 1x comes from
+			// the anticipated movement of the projectile on its frame of death, and
+			// 0.5x comes from the behaivor of BatchDrawList::Add.
```
Comment (Amazinite) [inline source/Projectile.cpp]:
```suggestion
			// 0.5x comes from the behavior of BatchDrawList::Add drawing the projectile sprite
			// half way between its current position and its next position.
```
