### PR TITLE
Fix frames lagging one frame behind rendering.

### LINKED ISSUE #6475: Killing shot appears after NPC death dialogue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using a weapon such as the dragonflame cannon to kill an NPC, the dialogue box appears before the shot is even made.

### Steps to Reproduce

* Accept a mission with a NPC to kill
* Damage the NPC enough so that you can 1-shot-kill it
* kill it using one shot (i.e. by using the dragonflame cannon)
* observe the dialogue box opening before the shot is fired

### Expected Behavior

the dialogue box appears after the shot is made (just wait a single frame even so it looks like it's happened?) which destroys the ship

### Screenshots

See video below:
[Video: https://1drv.ms/u/s!AhEogbCmotiYg5NMZhqqfxDjbcSKbQ?e=mGWTjk](https://1drv.ms/u/s!AhEogbCmotiYg5NMZhqqfxDjbcSKbQ?e=mGWTjk)

### Link to save file

Doesn't matter particularly which save file you use but here's mine:
[Save File: Elijha Letney.txt](https://github.com/endless-sky/endless-sky/files/7837516/Elijha.Letney.txt)

### Operating System

Windows 10 Home

### Game Source

GitHub Releases

### Game Version

Commit af34cc82e9e4c5eaaec96ff2bc5f6752f2d2fa32

### Additional Information

Was originally posted on discord: https://discord.com/channels/251118043411775489/536900466655887360/929769563770466335

### PR DESCRIPTION
**Pull request by quyykk**
**Bugfix:** This PR fixes #6475 

## Fix Details

The Engine::Draw() function used one frame before the one it should use, meaning that it was always one frame late. This PR fixes this issue by making it so that Draw() immediately uses the newly calculated draw lists.

## Testing Done

Used the save file from the linked issue to shoot the mission Korath to death. With this PR the kill shot appears behind the dialog as expected. I also used clang's thread sanitizer to verify that this PR doesn't introduce a new race condition.

## Save File

See the linked issue.

### CODE REVIEW

File: source/Engine.cpp [hunk 1]
```diff
@@ -1315,19 +1316,17 @@ void Engine::ThreadEntryPoint()
...
-				condition.wait(lock);
+			condition.wait(lock, [this] { return !hasFinishedCalculating || terminate; });
 
 			if(terminate)
 				break;
 		}
 
 		// Do all the calculations.
 		CalculateStep();
-
```
Comment (tehhowch) [inline source/Engine.cpp:1327]: Keep this newline. The braces are a block scope separate from the above line and should be easily identified as such.
