### PR TITLE
[Bugfix] Enable Full Sprite Definition for Minables

### LINKED ISSUE #10898: [Bug] Minable image sprites lack many image features
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The sprite definitions for minables seem to lack many features otherwise available for image definitions. So far, I've directly encountered:
- Inability to use `scale` to change the size of minables sprites
- Inability to use image blending modes (sprite filaname suffixes of +, =, etc)
- `frame rate` not working for animations (I think?)
- Probably more, this is just what I noticed immediately. Wouldn't surprise me if none of the basic sprite features were working honestly.

Okay yeah I spent 3 seconds checking the minables source file and this is the comment right above the sprite definition

> 		// A full sprite definition (frame rate, etc.) is not needed, because
>		// the frame rate will be set randomly and it will always be looping.

### Steps to Reproduce

Try to use any of the above image attributes in a minable definition.

e.g.

`minable "large water droplet"
	"display name" Large
	noun "Water Droplet"
	sprite "asteroid/large droplet/large droplet"
		scale 4
		"frame rate" 120
		"rewind"
		"random start frame"
	hull 1500
	"random hull" 600
	payload "Voidfish" 60
	explode puff`

### Expected Behavior

I would expect those image attributes to have their intended effects, and likewise with the blending modes.

### Screenshots

N/A

### Link to save file

N/A

### Operating System

Windows 11

### Game Source

Built from source

### Game Version

Whatever my master branch is running lmao

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Azure3141**
**Bug fix**

Resolves #10898 

## Summary
Using my master coding skills I was able to painstakingly replace a single line in mineables.cpp after hours of hard labor. This allows minable sprite definitions to be given all the attributes typical of a sprite definition elsewhere, such as scale, frame rate, etc. Existing minable definitions still function properly (as far as I can tell).

## Screenshots
As you can guess a Yottrite asteroid does not typically look like this. With these changes however, adding `scale` 10 to the sprite definition allows you to ruin the Yottrite economy forever.
489967c51c6f60986e947096716de840-1

## Usage examples
Minables can now be scaled, have their frame rate modified, use blending modes, etc.

## Testing Done
I crashed the Yottrite economy to get back at the Quarg. This was not sponsored by the Pug.

## Save File
Nah.

## Wiki Update
Probably needs one.

## Performance Impact
Maybe increases the load time for each defined minable/asteroid very slightly? Dunno.

### CODE REVIEW

**Comment by warp-core** [comment]
How about updating the comment above your change?
And, what about the properties that are either going to be discarded (framerate) or that we don't want to be changed (repeat)?
I don't want to merge this and then see new issues like: "bug: Minables ignore user set framerate" or "bug: Minables shouldn't stop repeating their animations even if I tell them to".

File: source/Minable.cpp [hunk 1]
```diff
@@ -180,7 +178,8 @@ void Minable::Place(double energy, double beltRadius)
 	// Start the object off with a random facing angle and spin rate.
 	angle = Angle::Random();
 	spin = Angle::Random(energy) - Angle::Random(energy);
-	SetFrameRate(Random::Real() * 4. * energy + 5.);
+	double frameRate = GetFrameRate() ? GetFrameRate() : Random::Real() * 4. * energy + 5.;
```
Comment (warp-core) [inline source/Minable.cpp:181]: Given that the default value framerate is not zero, this is not going to do what you want. I suggest checking the `DataNode` to see if a framerate value is provided in `Minable::Load` and set a `bool useRandomFramerate` field in `Minable` to `false` (the default should be `true`).

File: source/Minable.cpp [hunk 2]
```diff
@@ -77,10 +77,13 @@ void Minable::Load(const DataNode &node)
...
 		else if(key == "noun")
 			noun = child.Token(1);
-		// A full sprite definition (frame rate, etc.) is not needed, because
-		// the frame rate will be set randomly and it will always be looping.
 		else if(key == "sprite")
-			SetSprite(SpriteSet::Get(child.Token(1)));
+		{
+			LoadSprite(child);
+			for(const auto &grand : child)
+				if(grand.Token(0) == "frame rate")
```
Comment (warp-core) [inline source/Minable.cpp:84]:
```suggestion
				if(grand.Token(0) == "frame rate" || grand.Token(0) == "frame time")
```
