### PR TITLE
fix(mechanics): Apply fines for illegal mission passengers

### LINKED ISSUE #10084: Bug: Missions with only illegal passengers and not cargo are not illegal
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you take a mission with illegal passengers and not illegal cargo (e.g. the slave transport jobs or the shady passenger jobs), you cannot actually be fined or sentenced to death.

### Steps to Reproduce

1. Load the save
2. Depart
3. Wait for Hai authorities to scan you
4. See how you are not fined
5. Land on Everhope (security 1)
6. See how you are not fined

### Expected Behavior

If you are successfully scanned or caught by planetary security, you should be fined and the mission should fail.

### Screenshots

image

### Link to save file

[Remnant Test~Shady Passenger.txt](https://github.com/endless-sky/endless-sky/files/15370486/Remnant.Test.Shady.Passenger.txt)

### Operating System

Debian 12 Bookworm

### Game Source

GitHub Releases

### Game Version

v0.10.6

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by TomGoodIdea**
**Bug fix**
This PR fixes #10084.

## Summary
Fines for illegal passengers from missions are now correctly triggered. However, there's no in-flight scan that can detect illegal passengers, so such fines can only be applied on planets. There's still a chance to avoid detection, depending on the planetary `security` value.

## Testing Done
Tested with the save file provided in the original issue.

## Save File
See the original issue.

## Performance Impact
N/A

### CODE REVIEW

**Comment by ziproot** [comment]
Does this also work for atrocities?

**Review by ziproot — APPROVED** [review]
I have tested and it does in fact work with atrocities.
image

EDIT: This is what I got from landing on Lagrange with a slave mission active and this PR installed.

File: source/Politics.cpp [hunk 1]
```diff
@@ -35,13 +35,18 @@ namespace {
...
+				illegalPassengers += it.second;
 		// Illegal goods can be hidden inside legal goods to avoid detection.
-		const int contraband = ship.Cargo().IllegalCargoAmount();
+		const int contraband = cargo.IllegalCargoAmount() + illegalPassengers;
 		const int netIllegalCargo = contraband - ship.Attributes().Get("scan concealment");
 		if(netIllegalCargo <= 0)
 			return true;
 
-		const int legalGoods = ship.Cargo().Used() - contraband;
+		const int legalGoods = cargo.Used() - contraband + cargo.Passengers() - illegalPassengers;
```
Comment (tibetiroka) [inline source/Politics.cpp:49]: Contraband already had the illegal passengers, so I don't think it has to be subtracted again?

**Review by tibetiroka — COMMENTED** [review]
I'm not entirely convinced that passengers should be detected during scans. It probably makes sense from a balance perspective for the current missions, but it might be interesting if they could only be detected when landing on a planet (or being boarded?). That would let us better differentiate between freight and shuttle missions, providing different challenges - shuttle missions could be longer runs with lower per-jump risk.

I'm probably just overcomplicating things, though. Any thoughts?

**Comment by TomGoodIdea** [comment]
> I'm not entirely convinced that passengers should be detected during scans. It probably makes sense from a balance perspective for the current missions, but it might be interesting if they could only be detected when landing on a planet (or being boarded?). That would let us better differentiate between freight and shuttle missions, providing different challenges - shuttle missions could be longer runs with lower per-jump risk.

That would be doable and I have nothing against it, but let's wait for another opinion.

**Comment by Amazinite** [comment]
I'm in agreement with Tibe's idea. Cargo scanners and outfit scanners are for finding in cargo and installed illegal outfits. There's no indication that they would also be able to not only detect the number of people on board a ship (that's actually something the tactical scanner does), but also identify exactly who they are so that the scanners can check whether there is an arrest warrant out for them.

I wouldn't overcomplicate things by making it so that boarding acts as a scan of your passengers, but I do think it makes sense to only be able to check for illegal passengers when you land on a planet, as the spaceport personnel can presumably do more than just scan ships from the outside when checking them for contraband on landing.

**Comment by ziproot** [comment]
I concur with Amazinite. The slave transport missions already tend to be long distance, and while some of the shady passenger jobs are close by, that is explicitly mentioned as a selling point.

**Comment by TomGoodIdea** [comment]
I've tested it again and it still seems to work.

File: source/CargoHold.h [hunk 2]
```diff
@@ -111,6 +111,7 @@ class CargoHold {
 	// missions. If the returned value is negative, you are carrying something so
```
Comment (RisingLeaf) [inline source/CargoHold.h:111]: Can't request changes here, but it should be something or someone XD

File: source/Politics.cpp [hunk 3]
```diff
@@ -258,6 +258,37 @@ string Politics::Fine(PlayerInfo &player, const Government *gov, int scan, const
 
 		int failedMissions = 0;
 
+		if(!scan)
+		{
+			// Illegal passengers can only be detected by planetary security.
```
Comment (RisingLeaf) [inline source/Politics.cpp:263]: This comment has a weird position maybe move it in front of the if?

**Review by RisingLeaf — APPROVED** [review]

File: source/Politics.cpp [hunk 4]
```diff
@@ -258,6 +258,36 @@ string Politics::Fine(PlayerInfo &player, const Government *gov, int scan, const
...
+					if(!illegalCargoMessage.empty())
+					{
+						reason = ".\n\t";
+						reason.append(illegalCargoMessage);
+					}
+					// Fail any missions with illegal passengers and "stealth" set.
+					if(mission.IllegalCargoFine() > 0 && mission.Passengers() && mission.FailIfDiscovered())
+					{
+						player.FailMission(mission);
+						++failedMissions;
```
Comment (Amazinite) [inline source/Politics.cpp:286]: Looks like this would count the mission as failed twice if the mission has both illegal passengers and illegal cargo and both are caught.

Comment (TomGoodIdea) [reply source/Politics.cpp:286]: there's an IsFailed check a few lines above in both loops, so no?

Comment (Amazinite) [reply source/Politics.cpp:286]: Ah, I see. Yeah, that'll work.

File: source/Politics.cpp [hunk 5]
```diff
@@ -258,6 +258,36 @@ string Politics::Fine(PlayerInfo &player, const Government *gov, int scan, const
...
+				maxFine = fine;
+				reason = " for carrying illegal passengers.";
+
+				for(const Mission &mission : player.Missions())
+				{
+					if(mission.IsFailed(player))
+						continue;
+
+					// IllegalCargoMessage applies to both cargo and passengers.
+					string illegalCargoMessage = mission.IllegalCargoMessage();
```
Comment (Amazinite) [inline source/Politics.cpp:276]: I feel like we should just rename this function at this point. Thoughts?

Comment (TomGoodIdea) [reply source/Politics.cpp:276]: Would "FineMessage" be OK?

Comment (Amazinite) [reply source/Politics.cpp:276]: Yeah.
