### PR TITLE
fix(ui): Clear old messages every frame, and fix ship overheat message spam

### LINKED ISSUE #11640: The log fills up instantly with "Your ship is overheated" when moving/turning/firing
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When a key is held and the ship overheats, there is no debounce on the log message repeating, so it just spams.

I mean, this DOES help me see that something bad is happening, so maybe it's a feature?

### Steps to Reproduce

1. Attempt to move while overheated.

### Expected Behavior

One instance of "Your ship is overheated" displayed so long as that is the most recent message?

### Screenshots

Image

### Link to save file

_No response_

### Operating System

linux, ubuntu 24.04.2 LTS

### Game Source

Built from source

### Game Version

0.10.15 alpha

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by TomGoodIdea**
**Bug fix**

This PR addresses the bug described in issue #11640 (closes #11640).

## Acknowledgement

- [x] I acknowledge that I have read and understand the [Contributing](https://github.com/endless-sky/endless-sky/blob/master/docs/CONTRIBUTING.md) article.

## Summary
Adds a new special message importance level that uses the "highest" color, but "low" deduplication strategy, which means new messages will be added to the list only if there are no entries with the same text already.

Also noticed that removing old and invisible entries _after_ a new message appears, although doesn't make any difference for most importance levels, makes the "low"-deduplicated messages appear less frequently than they should: a new message isn't added because there already exists an invisible entry with the same text, and that entry doesn't get checked for removal, because the new message doesn't end up being added.

## Testing Done
yes™.

## Performance Impact
None.

### CODE REVIEW

File: source/Engine.cpp [hunk 1]
```diff
@@ -727,7 +727,7 @@ void Engine::Step(bool isActive)
 	}
 
 	if(flagship && flagship->IsOverheated())
-		Messages::Add("Your ship has overheated.", Messages::Importance::Highest);
+		Messages::Add("Your ship has overheated.", Messages::Importance::Overheat);
```
Comment (xobes) [inline source/Engine.cpp]: I don't love the case-specific name, but can't think of a generic one at the moment that would be better suited.

Comment (xobes) [reply source/Engine.cpp]:
```suggestion
		Messages::Add("Your ship has overheated.", Messages::Importance::HighestNoRepeat);
```

File: source/Messages.cpp [hunk 2]
```diff
@@ -74,7 +84,7 @@ const vector<Messages::Entry> &Messages::Get(int step, int animationDuration)
 
 		// If this message is not important and it is already being shown in the
 		// list, ignore it.
-		if(importance == Importance::Low)
+		if(importance == Importance::Low || importance == Importance::Overheat)
```
Comment (xobes) [inline source/Messages.cpp]:
```suggestion
		if(importance == Importance::Low || importance == Importance::HighestNoRepeat)
```

File: source/Messages.cpp [hunk 3]
```diff
@@ -135,6 +139,7 @@ const Color *Messages::GetColor(Importance importance, bool isLogPanel)
 	switch(importance)
 	{
 		case Messages::Importance::Highest:
+		case Messages::Importance::Overheat:
```
Comment (xobes) [inline source/Messages.cpp]:
```suggestion
		case Messages::Importance::HighestNoRepeat:
```

File: source/Messages.h [hunk 4]
```diff
@@ -37,7 +37,8 @@ class Messages {
 		High,
 		Info,
 		Daily,
-		Low
+		Low,
+		Overheat
```
Comment (xobes) [inline source/Messages.h]:
```suggestion
		HighestNoRepeat
```

File: source/Messages.cpp [hunk 5]
```diff
@@ -83,24 +93,18 @@ const vector<Messages::Entry> &Messages::Get(int step, int animationDuration)
...
 			// For each incoming message, if it exactly matches an existing message,
 			// replace that one with this new one by scheduling the old one for removal.
-			if(importance != Importance::Low && it->message == message && it->deathStep < 0)
-				it->deathStep = step + animationDuration;
-			// Erase messages that have reached the end of their lifetime.
-			if(age > 1000 + animationDuration || (it->deathStep >= 0 && it->deathStep <= step))
-				it = recent.erase(it);
-			else
-				++it;
+			if(importance != Importance::Low && importance != Importance::Overheat
```
Comment (xobes) [inline source/Messages.cpp]:
```suggestion
			if(importance != Importance::Low && importance != Importance::HighestNoRepeat
```

**Review by xobes — CHANGES_REQUESTED** [review]

**Review by xobes — APPROVED** [review]

**Review by xobes — APPROVED** [review]
