### PR TITLE
Park off-system escorts that fail flight checks + insufficient bunks check

### LINKED ISSUE #5165: [bug] Off-system Escorts fly away to other systems with only steering Engines
Unparking off-system escorts that are not equipped with thruster engines does not stop them from jumping to other systems.

1. Park an escort.
2. Sell escorts' thruster engines (so that the ship only has steering engines).
3. Take off and jump to a far away system.
4. Land and unpark escort.
5. Takeoff and wait for escorts to start jumping systems.

Expected behavior:
Game should not let you unpark escorts and takeoff while any off-system escorts fail flight checks (engines, power, heat).

Here is a screenshot: You can see the ship description that it does not have any thruster engines, and in the lower left you can see 4 ships of similar specs.
image

System:
 - OS:Windows 10 Pro 64-bit build 18363
 - Game Source: Steam
 - Version: 0.9.12

Save file:
When you load the save file, once you takeoff, you can immediately see the thruster-less ships on the bottom left jumping systems.
[Ember Serebryakova.txt](https://github.com/endless-sky/endless-sky/files/4943801/Ember.Serebryakova.txt)

Additional info:
When I unparked these ships, I was on Glaze in the Aldhibain system.
Issue looks related to #5133

Temporary fix:
I managed to herd the ships back to a spaceport with an outfitter. 

Apparently, once you take off from a planet, the ships are able to jump ONCE, after which they are unable to come to a stop and continue to float away. However, if you land and takeoff again they will be able to do another jump. You can repeat this until the ships come to a planet with an outfitter. 

If, however, the ships run out of fuel in a system with a habitable planet before they can reach an outfitter, you can go to that system, land (and hence refuel them), park the escorts(because the game wont let you takeoff if the escorts dont have engines), go to another system, and unpark them. Then you can continue to land and takeoff repeatedly to make the thruster-less ships jump.

It can get worse however. If the ships run out of fuel in an uninhabited system, you can not refuel them by landing, and you cannot simply board them either because when you jump into the system, they are drifting off at such a speed that they cannot be boarded. The solution here is to select the escort in question(by clicking on them) and disable them by firing at them. Disabling ships removes any velocity they have so they come a stop. This way you can board them to repair and refuel them.

### PR DESCRIPTION
**Pull request by Amazinite**
**Bugfix:** This PR is a reopening of #5654, which fixes #5165 and #5708.

## Fix Details
#5654 replaced the existing flight checks system with a new dialog which asks if you want to park the ships that fail their flight checks. @Hurleveur noted in that PR though that the existing flight check conversations are actually pretty nice:
> Lore and stuff isn't my area of expertise, but I personally liked the conversations with problems to launch, especially from an immersion standpoint.
> Maybe we could just make it give the big dialog only if the ship is in the same system, and the quick one otherwise?

So this PR will take that suggestion, providing a dialog for off-system escorts being unable to launch of that happens, but still providing the existing conversations for those ships that are with you.

#5654 also made it so that ships with warnings or errors are highlighted in the ships list of the player info panel. I've removed this UI change from this PR, as it isn't necessary for the two bug fixes.
image

## Testing Done
Using the save file attached below:
1) Attempt to take off from Earth. Receive flight check conversation about one of my Furies.
2) Park the Fury and land in another system.
3) Unpark the Fury and attempt to take off. This time receive dialog saying that out-of-system ships with flight errors will be parked.

## Save File
[Test Pilot.txt](https://github.com/endless-sky/endless-sky/files/10414452/Test.Pilot.txt)

### CODE REVIEW

File: source/PlanetPanel.cpp [hunk 1]
```diff
@@ -246,20 +248,57 @@ void PlanetPanel::TakeOffIfReady()
...
+						*GameData::Conversations().Get("flight check: " + check), nullptr, result.first));
+					return;
+				}
 			}
 		}
+		if(!absentCannotFly.empty())
+		{
+			string shipNames = out.str();
+			shipNames.pop_back();
+			shipNames.pop_back();
```
Comment (Hurleveur) [inline source/PlanetPanel.cpp:283]: Why do we pop out the last two elements? Its the ",\n" I recon but could use a small comment?

File: source/PlayerInfoPanel.cpp [hunk 2]
```diff
@@ -809,6 +845,23 @@ void PlayerInfoPanel::DrawFleet(const Rectangle &bounds)
 			pos.Y() += 20.;
 		}
 	}
+	// Show tooltip that tells what is wrong with the ship under the mouse.
+	else if(error || warning)
+	{
+		constexpr int WIDTH = 250;
+		constexpr int PAD = 10;
```
Comment (Hurleveur) [inline source/PlayerInfoPanel.cpp:852]: What about defining these two in interface.txt? Could be for another PR.

File: source/Ship.cpp [hunk 3]
```diff
@@ -1204,6 +1204,8 @@ vector<string> Ship::FlightCheck() const
 		checks.emplace_back("no thruster!");
 	else if(!turn)
 		checks.emplace_back("no steering!");
+	else if(attributes.Get("required crew") > attributes.Get("bunks"))
```
Comment (Hurleveur) [inline source/Ship.cpp:1207]: Shouldnt we do it the same way as the rest, by putting it in a variable? I imagine its done for readability

**Review by Hurleveur — COMMENTED** [review]
Everything looks good to me just some small things
I love the idea of the warning that shows up when you select it, some testing will be good for sure though

File: source/PlayerInfoPanel.cpp (hunk 2 above)
Comment (Amazinite) [reply source/PlayerInfoPanel.cpp:852]: Per the PR description, I think I might actually just pull the changes to the player info panel out. This is really just a new UI feature, not a bug fix.

File: source/Ship.cpp (hunk 3 above)
Comment (Amazinite) [reply source/Ship.cpp:1207]: Doesn't seem necessary. Many of those variables are used multiple times or in more complex checks. They're also all doubles. This is just a single greater than check. Even if I made a variable `bunks - crew`, this would still have to be `var < 0`.

File: source/PlanetPanel.cpp [hunk 4]
```diff
@@ -230,6 +230,8 @@ void PlanetPanel::TakeOffIfReady()
 	// to take off until the button is clicked again.
 	requestedLaunch = false;
 
+	absentCannotFly.clear();
```
Comment (Hurleveur) [inline source/PlanetPanel.cpp:233]: wasnt this already cleared by checkwarningsandtakeoff?

File: source/PlanetPanel.cpp [hunk 5]
```diff
@@ -246,20 +248,58 @@ void PlanetPanel::TakeOffIfReady()
...
 			}
 		}
+		if(!absentCannotFly.empty())
+		{
+			string shipNames = out.str();
+			// Pop back the last ", " in the string.
+			shipNames.pop_back();
+			shipNames.pop_back();
+			GetUI()->Push(new Dialog(this, &PlanetPanel::CheckWarningsAndTakeOff,
+				"Some of your ships that are not with you are not be able to fly:\n" + shipNames +
```
Comment (Hurleveur) [inline source/PlanetPanel.cpp:286]:
```suggestion
				"Some of your ships in other systems are not be able to fly:\n" + shipNames +
```
I feel like its clearer like that

File: source/PlanetPanel.cpp (hunk 4 above)
Comment (Amazinite) [reply source/PlanetPanel.cpp:233]: If the player declines the dialog then no.

**Review by Hurleveur — APPROVED** [review]
Looks good to me code wise, and the scope was reduced so its very simple
We could only generate the vectors once instead of redoing it at each take off attempt but since its happening when the game is paused this way should be fine and mb even less prone to errors.

**Comment by Hurleveur** [comment]
Could be good if smbd was to take a look at the new conversation, like @tibetiroka

File: data/conversations.txt [hunk 6]
```diff
@@ -31,3 +31,8 @@ conversation "flight check: overheating!"
...
+
+conversation "flight check: insufficient crew!"
+	scene "scene/engine"
+	`You've heard enough horror stories about the sort of accidents that happen when starship systems malfunction to be completely convinced of the necessity of a pre-flight safety check. As you listen to the complex symphony of hums, rattles, and clicks of the <ship> warming up, you run through a mental checklist. Computers: check. Life support: check.`
+	`	But when you reach the end of the checklist, although nothing appears wrong, you have a sneaking suspicion that something isn't right. You go through the checklist again, but the suspicion only grows. You decide to check the specifications of the ship and each of the outfits you have installed and finally find the issue that was scratching at the back of your mind: you've somehow managed to outfit <ship> to require more crew than it has space for. You are going to have to either install more bunk rooms, or trade out some components that require extra crew, lest the ship come crashing down during takeoff as a result of not having enough crew to man all the necessary systems.`
```
Comment (tibetiroka) [inline data/conversations.txt:38]:
```suggestion
	`	But when you reach the end of the checklist, although nothing appears wrong, you have a sneaking suspicion that something isn't right. You go through the checklist again, but the suspicion only grows. You decide to check the specifications of the ship and each of the outfits you have installed and finally find the issue that was scratching at the back of your mind: you've somehow managed to outfit the <ship> to require more crew than it has space for. You are going to have to either install more bunk rooms, or trade out some components that require extra crew, lest the ship come crashing down during takeoff as a result of not having enough crew to man all the necessary systems.`
```

**Review by tibetiroka — CHANGES_REQUESTED** [review]

**Review by tibetiroka — APPROVED** [review]

**Comment by Quantumshark** [comment]
This insufficient bunks check seems to be triggering for ships with `automaton` if they have outfits with required crew.
